<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>1413851</PostId><Url>http://stackoverflow.com/questions/1413851</Url><Stack><Type>ArgumentError</Type><Message>argument 1:</Message><Frame><File>C:\....\.FROGmoduleTEST.py</File><Line>243</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>4439361</PostId><Url>http://stackoverflow.com/questions/4439361</Url><Stack><Type>ArgumentError</Type><Message>Python argument types in</Message><Frame><File>C:\bladiebla\script.py</File><Line>8</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>10692191</PostId><Url>http://stackoverflow.com/questions/10692191</Url><Stack><Type>ArgumentError</Type><Message>An error occurred parsing (locally or remotely) the arguments to datastore_v3.Put()</Message><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/_webapp25.py</File><Line>703</Line><Method>__call__</Method></Frame><Frame><File>/base/data/home/apps/s~jupitersfolly/4.357517623694016771/controller/frequest.py</File><Line>57</Line><Method>post</Method></Frame><Frame><File>/base/data/home/apps/s~jupitersfolly/4.357517623694016771/controller/frequest.py</File><Line>78</Line><Method>order</Method></Frame><Frame><File>/base/data/home/apps/s~jupitersfolly/4.357517623694016771/model/game.py</File><Line>355</Line><Method>update</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/datastore.py</File><Line>2433</Line><Method>RunInTransaction</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/datastore.py</File><Line>2571</Line><Method>RunInTransactionOptions</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/datastore.py</File><Line>2593</Line><Method>_DoOneTry</Method></Frame><Frame><File>/base/data/home/apps/s~jupitersfolly/4.357517623694016771/model/game.py</File><Line>348</Line><Method>transactional_update</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/ext/db/__init__.py</File><Line>1074</Line><Method>put</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/datastore.py</File><Line>579</Line><Method>Put</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/apiproxy_stub_map.py</File><Line>604</Line><Method>get_result</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/datastore/datastore_rpc.py</File><Line>1577</Line><Method>__put_hook</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/datastore/datastore_rpc.py</File><Line>1212</Line><Method>check_rpc_success</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/apiproxy_stub_map.py</File><Line>570</Line><Method>check_success</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/apiproxy_rpc.py</File><Line>133</Line><Method>CheckSuccess</Method></Frame></Stack></Post><Post><PostId>10901173</PostId><Url>http://stackoverflow.com/questions/10901173</Url><Stack><Type>ArgumentError</Type><Message>Python argument types in</Message><Frame><File>...\foo.py</File><Line>22</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>19461274</PostId><Url>http://stackoverflow.com/questions/19461274</Url><Stack><Type>ArgumentError</Type><Message>Python argument types in</Message><Frame><File>test2.py</File><Line>18</Line><Method>test_globals</Method></Frame></Stack></Post></Posts>