<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>13944427</PostId><Url>http://stackoverflow.com/questions/13944427</Url><Stack><Type>DbfError</Type><Message>D:\Data_RP\data\projects\kN\GIS\shapes\SWM_4N.dbf is closed; record 0 is unavailable</Message><Frame><File>pyshell#24</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Python27\ArcGIS10.1\lib\site-packages\dbf.py</File><Line>3379</Line><Method>__getattr__</Method></Frame><Frame><File>D:\Data_RP\data\projects\kN\GIS\python\04_convert_dbf_ALT.py</File><Line>31</Line><Method>module</Method></Frame><Frame><File>C:\Python27\ArcGIS10.1\lib\site-packages\dbf.py</File><Line>5670</Line><Method>export</Method></Frame><Frame><File>C:\Python27\ArcGIS10.1\lib\site-packages\dbf.py</File><Line>3384</Line><Method>__getitem__</Method></Frame><Frame><File>C:\Python27\ArcGIS10.1\lib\site-packages\dbf.py</File><Line>3175</Line><Method>__getitem__</Method></Frame></Stack></Post><Post><PostId>13944427</PostId><Url>http://stackoverflow.com/questions/13944427</Url><Stack><Type>DbfError</Type><Message>D:\Data_RP\data\projects\kN\GIS\shapes\SWM_4N.dbf is closed; record 0 is unavailable</Message><Frame><File>pyshell#24</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Python27\ArcGIS10.1\lib\site-packages\dbf.py</File><Line>3379</Line><Method>__getattr__</Method></Frame><Frame><File>D:\Data_RP\data\projects\kN\GIS\python\04_convert_dbf_ALT.py</File><Line>31</Line><Method>module</Method></Frame><Frame><File>C:\Python27\ArcGIS10.1\lib\site-packages\dbf.py</File><Line>5670</Line><Method>export</Method></Frame><Frame><File>C:\Python27\ArcGIS10.1\lib\site-packages\dbf.py</File><Line>3384</Line><Method>__getitem__</Method></Frame><Frame><File>C:\Python27\ArcGIS10.1\lib\site-packages\dbf.py</File><Line>3175</Line><Method>__getitem__</Method></Frame></Stack></Post></Posts>