<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>5554100</PostId><Url>http://stackoverflow.com/questions/5554100</Url><Stack><Type>DeadlineExceededError</Type><Message>ApplicationError: 5</Message><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py</File><Line>636</Line><Method>__call__</Method></Frame><Frame><File>/base/data/home/apps/netlicense/3.349495357411133950/main.py</File><Line>235</Line><Method>post</Method></Frame><Frame><File>/base/data/home/apps/netlicense/3.349495357411133950/facebook.py</File><Line>149</Line><Method>put_wall_post</Method></Frame><Frame><File>/base/data/home/apps/netlicense/3.349495357411133950/facebook.py</File><Line>131</Line><Method>put_object</Method></Frame><Frame><File>/base/data/home/apps/netlicense/3.349495357411133950/facebook.py</File><Line>179</Line><Method>request</Method></Frame><Frame><File>/base/python_runtime/python_dist/lib/python2.5/urllib2.py</File><Line>124</Line><Method>urlopen</Method></Frame><Frame><File>/base/python_runtime/python_dist/lib/python2.5/urllib2.py</File><Line>381</Line><Method>open</Method></Frame><Frame><File>/base/python_runtime/python_dist/lib/python2.5/urllib2.py</File><Line>399</Line><Method>_open</Method></Frame><Frame><File>/base/python_runtime/python_dist/lib/python2.5/urllib2.py</File><Line>360</Line><Method>_call_chain</Method></Frame><Frame><File>/base/python_runtime/python_dist/lib/python2.5/urllib2.py</File><Line>1115</Line><Method>https_open</Method></Frame><Frame><File>/base/python_runtime/python_dist/lib/python2.5/urllib2.py</File><Line>1080</Line><Method>do_open</Method></Frame><Frame><File>/base/python_runtime/python_dist/lib/python2.5/httplib.py</File><Line>197</Line><Method>getresponse</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/urlfetch.py</File><Line>260</Line><Method>fetch</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/apiproxy_stub_map.py</File><Line>592</Line><Method>get_result</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/urlfetch.py</File><Line>361</Line><Method>_get_fetch_result</Method></Frame></Stack></Post><Post><PostId>5738146</PostId><Url>http://stackoverflow.com/questions/5738146</Url><Stack><Type>DeadlineExceededError</Type><Message>The API call urlfetch.Fetch() took too long to respond and was cancelled.</Message><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py</File><Line>636</Line><Method>__call__</Method></Frame><Frame><File>/base/data/home/apps/tweethitapp/1.349863151373877476/tweethit/handlers/taskworker.py</File><Line>80</Line><Method>post</Method></Frame><Frame><File>/base/data/home/apps/tweethitapp/1.349863151373877476/tweethit/utils/rpc.py</File><Line>98</Line><Method>fetch_urls</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/apiproxy_stub_map.py</File><Line>592</Line><Method>get_result</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/urlfetch.py</File><Line>345</Line><Method>_get_fetch_result</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/apiproxy_stub_map.py</File><Line>558</Line><Method>check_success</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/apiproxy_rpc.py</File><Line>133</Line><Method>CheckSuccess</Method></Frame></Stack></Post><Post><PostId>6453003</PostId><Url>http://stackoverflow.com/questions/6453003</Url><Stack><Type>DeadlineExceededError</Type><Message>ApplicationError: 5</Message><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py</File><Line>700</Line><Method>__call__</Method></Frame><Frame><File>/base/data/home/apps/s~malware-app/7.351334968546050391/main.py</File><Line>505</Line><Method>get</Method></Frame><Frame><File>/base/python_runtime/python_dist/lib/python2.5/urllib2.py</File><Line>124</Line><Method>urlopen</Method></Frame><Frame><File>/base/python_runtime/python_dist/lib/python2.5/urllib2.py</File><Line>381</Line><Method>open</Method></Frame><Frame><File>/base/python_runtime/python_dist/lib/python2.5/urllib2.py</File><Line>399</Line><Method>_open</Method></Frame><Frame><File>/base/python_runtime/python_dist/lib/python2.5/urllib2.py</File><Line>360</Line><Method>_call_chain</Method></Frame><Frame><File>/base/python_runtime/python_dist/lib/python2.5/urllib2.py</File><Line>1114</Line><Method>http_open</Method></Frame><Frame><File>/base/python_runtime/python_dist/lib/python2.5/urllib2.py</File><Line>1087</Line><Method>do_open</Method></Frame><Frame><File>/base/python_runtime/python_dist/lib/python2.5/httplib.py</File><Line>197</Line><Method>getresponse</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/urlfetch.py</File><Line>260</Line><Method>fetch</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/apiproxy_stub_map.py</File><Line>592</Line><Method>get_result</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/urlfetch.py</File><Line>364</Line><Method>_get_fetch_result</Method></Frame></Stack></Post><Post><PostId>9069003</PostId><Url>http://stackoverflow.com/questions/9069003</Url><Stack><Type>DeadlineExceededError</Type><Message>ApplicationError: 5</Message><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>1511</Line><Method>__call__</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>1505</Line><Method>__call__</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>1253</Line><Method>default_dispatcher</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>1077</Line><Method>__call__</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>547</Line><Method>dispatch</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>545</Line><Method>dispatch</Method></Frame><Frame><File>/base/data/home/apps/s~montaoproject/gralumo.356457066048686089/main.py</File><Line>1575</Line><Method>post</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/1/google/appengine/api/urlfetch.py</File><Line>263</Line><Method>fetch</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py</File><Line>592</Line><Method>get_result</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/1/google/appengine/api/urlfetch.py</File><Line>371</Line><Method>_get_fetch_result</Method></Frame></Stack></Post><Post><PostId>9191591</PostId><Url>http://stackoverflow.com/questions/9191591</Url><Stack><Type>DeadlineExceededError</Type><Message>The API call file.Create() took too long to respond and was cancelled.</Message><Frame><File>/base/data/home/apps/s~czongae/1.356669185377832769/webapp2.py</File><Line>1516</Line><Method>__call__</Method></Frame><Frame><File>/base/data/home/apps/s~czongae/1.356669185377832769/webapp2.py</File><Line>1510</Line><Method>__call__</Method></Frame><Frame><File>/base/data/home/apps/s~czongae/1.356669185377832769/webapp2.py</File><Line>1258</Line><Method>default_dispatcher</Method></Frame><Frame><File>/base/data/home/apps/s~czongae/1.356669185377832769/webapp2.py</File><Line>1082</Line><Method>__call__</Method></Frame><Frame><File>/base/data/home/apps/s~czongae/1.356669185377832769/webapp2.py</File><Line>552</Line><Method>dispatch</Method></Frame><Frame><File>/base/data/home/apps/s~czongae/1.356669185377832769/webapp2.py</File><Line>550</Line><Method>dispatch</Method></Frame><Frame><File>/base/data/home/apps/s~czongae/1.356669185377832769/main.py</File><Line>43</Line><Method>get</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/files/blobstore.py</File><Line>69</Line><Method>create</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/files/file.py</File><Line>491</Line><Method>_create</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/files/file.py</File><Line>234</Line><Method>_make_call</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/apiproxy_stub_map.py</File><Line>558</Line><Method>check_success</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/apiproxy_rpc.py</File><Line>133</Line><Method>CheckSuccess</Method></Frame></Stack></Post><Post><PostId>13051628</PostId><Url>http://stackoverflow.com/questions/13051628</Url><Stack><Type>DeadlineExceededError</Type><Message>Deadline exceeded while waiting for HTTP response from URL: https://graph.facebook.com/me/photos?access_token=</Message><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/_webapp25.py</File><Line>710</Line><Method>__call__</Method></Frame><Frame><File>/base/data/home/apps/s~digibackapi/1.362663258877230387/main.py</File><Line>512</Line><Method>get</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/urlfetch.py</File><Line>266</Line><Method>fetch</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/apiproxy_stub_map.py</File><Line>604</Line><Method>get_result</Method></Frame><Frame><File>/base/python_runtime/python_lib/versions/1/google/appengine/api/urlfetch.py</File><Line>404</Line><Method>_get_fetch_result</Method></Frame></Stack></Post><Post><PostId>15952813</PostId><Url>http://stackoverflow.com/questions/15952813</Url><Stack><Type>DeadlineExceededError</Type><Message>The API call file.Close() took too long to respond and was cancelled.</Message><Frame><File>/base/data/home/apps/s~steprep-prod-hrd/prod-339.366560204640641232/lib/mapreduce/handlers.py</File><Line>182</Line><Method>handle</Method></Frame><Frame><File>/base/data/home/apps/s~steprep-prod-hrd/prod-339.366560204640641232/lib/mapreduce/handlers.py</File><Line>263</Line><Method>process_inputs</Method></Frame><Frame><File>/base/data/home/apps/s~steprep-prod-hrd/prod-339.366560204640641232/lib/mapreduce/handlers.py</File><Line>318</Line><Method>process_data</Method></Frame><Frame><File>/base/data/home/apps/s~steprep-prod-hrd/prod-339.366560204640641232/lib/mapreduce/output_writers.py</File><Line>711</Line><Method>write</Method></Frame><Frame><File>/base/data/home/apps/s~steprep-prod-hrd/prod-339.366560204640641232/lib/mapreduce/output_writers.py</File><Line>266</Line><Method>append</Method></Frame><Frame><File>/base/data/home/apps/s~steprep-prod-hrd/prod-339.366560204640641232/lib/mapreduce/output_writers.py</File><Line>288</Line><Method>flush</Method></Frame><Frame><File>/python27_runtime/python27_lib/versions/1/google/appengine/api/files/file.py</File><Line>297</Line><Method>__exit__</Method></Frame><Frame><File>/python27_runtime/python27_lib/versions/1/google/appengine/api/files/file.py</File><Line>291</Line><Method>close</Method></Frame><Frame><File>/python27_runtime/python27_lib/versions/1/google/appengine/api/files/file.py</File><Line>427</Line><Method>_make_rpc_call_with_retry</Method></Frame><Frame><File>/python27_runtime/python27_lib/versions/1/google/appengine/api/files/file.py</File><Line>250</Line><Method>_make_call</Method></Frame><Frame><File>/python27_runtime/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py</File><Line>570</Line><Method>check_success</Method></Frame><Frame><File>/python27_runtime/python27_lib/versions/1/google/appengine/api/apiproxy_rpc.py</File><Line>133</Line><Method>CheckSuccess</Method></Frame></Stack></Post><Post><PostId>19445682</PostId><Url>http://stackoverflow.com/questions/19445682</Url><Stack><Type>DeadlineExceededError</Type><Message>The API call remote_socket.Receive() took too long to respond and was cancelled.</Message><Frame><File>/base/data/home/runtimes/python27/python27_dist/lib/python2.7/imaplib.py</File><Line>760</Line><Method>uid</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_dist/lib/python2.7/imaplib.py</File><Line>1070</Line><Method>_simple_command</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_dist/lib/python2.7/imaplib.py</File><Line>897</Line><Method>_command_complete</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_dist/lib/python2.7/imaplib.py</File><Line>999</Line><Method>_get_tagged_response</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_dist/lib/python2.7/imaplib.py</File><Line>916</Line><Method>_get_response</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_dist/lib/python2.7/imaplib.py</File><Line>1009</Line><Method>_get_line</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_dist/lib/python2.7/imaplib.py</File><Line>1171</Line><Method>readline</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_dist/lib/python2.7/socket.py</File><Line>445</Line><Method>readline</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_dist/lib/python2.7/ssl.py</File><Line>301</Line><Method>recv</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_dist/lib/python2.7/ssl.py</File><Line>220</Line><Method>read</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/remote_socket/_remote_socket.py</File><Line>864</Line><Method>recv</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/remote_socket/_remote_socket.py</File><Line>903</Line><Method>recvfrom</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py</File><Line>94</Line><Method>MakeSyncCall</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py</File><Line>328</Line><Method>MakeSyncCall</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_rpc.py</File><Line>133</Line><Method>CheckSuccess</Method></Frame></Stack></Post><Post><PostId>24677654</PostId><Url>http://stackoverflow.com/questions/24677654</Url><Stack><Type>DeadlineExceededError</Type><Message>The API call urlfetch.Fetch() took too long to respond and was cancelled.</Message><Frame><File>/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py</File><Line>1535</Line><Method>__call__</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py</File><Line>1529</Line><Method>__call__</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py</File><Line>1278</Line><Method>default_dispatcher</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py</File><Line>1102</Line><Method>__call__</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py</File><Line>572</Line><Method>dispatch</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py</File><Line>570</Line><Method>dispatch</Method></Frame><Frame><File>/base/data/home/apps/s~neediz-ws-splitpdf/1.377128135913812779/main.py</File><Line>219</Line><Method>work</Method></Frame><Frame><File>/base/data/home/apps/s~neediz-ws-splitpdf/1.377128135913812779/main.py</File><Line>161</Line><Method>retrieve_all_files</Method></Frame><Frame><File>lib/oauth2client/util.py</File><Line>132</Line><Method>positional_wrapper</Method></Frame><Frame><File>lib/apiclient/http.py</File><Line>716</Line><Method>execute</Method></Frame><Frame><File>lib/oauth2client/util.py</File><Line>132</Line><Method>positional_wrapper</Method></Frame><Frame><File>lib/oauth2client/client.py</File><Line>490</Line><Method>new_request</Method></Frame><Frame><File>lib/httplib2/__init__.py</File><Line>1570</Line><Method>request</Method></Frame><Frame><File>lib/httplib2/__init__.py</File><Line>1317</Line><Method>_request</Method></Frame><Frame><File>lib/httplib2/__init__.py</File><Line>1286</Line><Method>_conn_request</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_dist/lib/python2.7/gae_override/httplib.py</File><Line>520</Line><Method>getresponse</Method></Frame><Frame><File>lib/httplib2/__init__.py</File><Line>1089</Line><Method>fixed_fetch</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/urlfetch.py</File><Line>270</Line><Method>fetch</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py</File><Line>612</Line><Method>get_result</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/urlfetch.py</File><Line>375</Line><Method>_get_fetch_result</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py</File><Line>578</Line><Method>check_success</Method></Frame><Frame><File>/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_rpc.py</File><Line>133</Line><Method>CheckSuccess</Method></Frame></Stack></Post></Posts>