<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>13131825</PostId><Url>http://stackoverflow.com/questions/13131825</Url><Stack><Type>FileNotFoundError</Type><Message>[WinError 2] The system cannot find the file specified</Message><Frame><File>C:\Python33\lib\subprocess.py</File><Line>1090</Line><Method>_execute_child</Method></Frame></Stack></Post><Post><PostId>13416549</PostId><Url>http://stackoverflow.com/questions/13416549</Url><Stack><Type>FileNotFoundError</Type><Message>[WinError 3] The system cannot find the path specified: '.\\Drivers\\Intel Drivers\\Applications\\Software\\Applications\\Wave_Embassy_Trust_Suite\\EMBASSY Security Center\\program files\\Wave Systems Corp\\EMBASSY Security Center\\plugins\\cpm.scp\\webinterface\\zh-CHS\\AccessingToolkit.htm'</Message><Frame><File>C:\SyncClientRK\SyncClientRK.py</File><Line>183</Line><Method>module</Method></Frame><Frame><File>C:\SyncClientRK\SyncClientRK.py</File><Line>17</Line><Method>__init__</Method></Frame><Frame><File>C:\SyncClientRK\SyncClientRK.py</File><Line>38</Line><Method>getStatus</Method></Frame><Frame><File>C:\SyncClientRK\SyncClientRK.py</File><Line>53</Line><Method>generateLocalStatus</Method></Frame><Frame><File>C:\Python33\lib\genericpath.py</File><Line>54</Line><Method>getmtime</Method></Frame></Stack></Post><Post><PostId>15440053</PostId><Url>http://stackoverflow.com/questions/15440053</Url><Stack><Type>FileNotFoundError</Type><Message>[WinError 3] The system cannot find the path specified: 'test\\*.*'</Message><Frame><File>pyshell#0</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Users\Phuchu\Desktop\Python\homework8.py</File><Line>65</Line><Method>traverse</Method></Frame></Stack></Post><Post><PostId>16576478</PostId><Url>http://stackoverflow.com/questions/16576478</Url><Stack><Type>FileNotFoundError</Type><Message>[WinError 2] The system cannot find the file specified</Message><Frame><File>C:\Python33\lib\subprocess.py</File><Line>1106</Line><Method>_execute_child</Method></Frame><Frame><File>C:\Users\user\Workspace\PythonConverter\HTMLandPythonConverter\Converter.py</File><Line>77</Line><Method>module</Method></Frame><Frame><File>C:\Users\user\Workspace\PythonConverter\HTMLandPythonConverter\Converter.py</File><Line>47</Line><Method>massConvert</Method></Frame><Frame><File>C:\Users\user\Workspace\PythonConverter\HTMLandPythonConverter\Converter.py</File><Line>61</Line><Method>convertVideotoNewFormat</Method></Frame><Frame><File>C:\Python33\lib\subprocess.py</File><Line>820</Line><Method>__init__</Method></Frame><Frame><File>C:\Python33\lib\subprocess.py</File><Line>1112</Line><Method>_execute_child</Method></Frame></Stack></Post><Post><PostId>16576478</PostId><Url>http://stackoverflow.com/questions/16576478</Url><Stack><Type>FileNotFoundError</Type><Message>[WinError 2] The system cannot find the file specified</Message><Frame><File>C:\Python33\lib\subprocess.py</File><Line>1106</Line><Method>_execute_child</Method></Frame><Frame><File>C:\Users\user\Workspace\PythonConverter\HTMLandPythonConverter\Converter.py</File><Line>77</Line><Method>module</Method></Frame><Frame><File>C:\Users\user\Workspace\PythonConverter\HTMLandPythonConverter\Converter.py</File><Line>47</Line><Method>massConvert</Method></Frame><Frame><File>C:\Users\user\Workspace\PythonConverter\HTMLandPythonConverter\Converter.py</File><Line>61</Line><Method>convertVideotoNewFormat</Method></Frame><Frame><File>C:\Python33\lib\subprocess.py</File><Line>820</Line><Method>__init__</Method></Frame><Frame><File>C:\Python33\lib\subprocess.py</File><Line>1112</Line><Method>_execute_child</Method></Frame></Stack></Post><Post><PostId>17453165</PostId><Url>http://stackoverflow.com/questions/17453165</Url><Stack><Type>FileNotFoundError</Type><Message>[WinError 2]</Message><Frame><File>C:\Python33\lib\subprocess.py</File><Line>1106</Line><Method>_execute_child</Method></Frame></Stack></Post><Post><PostId>17658856</PostId><Url>http://stackoverflow.com/questions/17658856</Url><Stack><Type>FileNotFoundError</Type><Message>[Errno 2] No such file or directory: 'test.rtf'</Message><Frame><File>/Users/AshleyStallings/Documents/School Work/Computer Programming/Side Projects/How many? (Python).py</File><Line>9</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>17866564</PostId><Url>http://stackoverflow.com/questions/17866564</Url><Stack><Type>FileNotFoundError</Type><Message>[WinError 3] The system cannot find the path specified: 'C:\\Users\\harridr3\\Desktop\\New folder\\ABL Lights\\2344327-ABL Lights-PackagingForm-00/00/00.xlsx'</Message><Frame><File>pyshell#22</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Users\harridr3\Desktop\python testing\renaming.py</File><Line>52</Line><Method>excelwriter</Method></Frame></Stack></Post><Post><PostId>18522273</PostId><Url>http://stackoverflow.com/questions/18522273</Url><Stack><Type>FileNotFoundError</Type><Message>[Errno 2] No such file or directory: 'data/my_data.txt'</Message><Frame><File>./bin/my_script.py</File><Line>87</Line><Method>module</Method></Frame><Frame><File>./bin/my_script.py</File><Line>61</Line><Method>run</Method></Frame><Frame><File>C:\Users\XXXX\Desktop\scripts\bin\tables.py</File><Line>12</Line><Method>load_data</Method></Frame><Frame><File>C:\Users\XXXX\Desktop\scripts\bin\fileutil.py</File><Line>5</Line><Method>read_file</Method></Frame></Stack></Post><Post><PostId>19032509</PostId><Url>http://stackoverflow.com/questions/19032509</Url><Stack><Type>FileNotFoundError</Type><Message>[Errno 2] No such file or directory: 'nd1.txt'</Message><Frame><File>E:\Documents\Information Retrieval\postingsList.py</File><Line>39</Line><Method>module</Method></Frame><Frame><File>E:\Documents\Information Retrieval\postingsList.py</File><Line>36</Line><Method>main</Method></Frame><Frame><File>E:\Documents\Information Retrieval\postingsList.py</File><Line>28</Line><Method>parseDirectory</Method></Frame><Frame><File>E:\Documents\Information Retrieval\postingsList.py</File><Line>28</Line><Method>listcomp</Method></Frame></Stack></Post><Post><PostId>19413951</PostId><Url>http://stackoverflow.com/questions/19413951</Url><Stack><Type>FileNotFoundError</Type><Message>[WinError 2] The system cannot find the file specified</Message><Frame><File>C:/Users/pc/Google Drive/Python/tshark1.py</File><Line>6</Line><Method>module</Method></Frame><Frame><File>C:\Python33\lib\subprocess.py</File><Line>820</Line><Method>__init__</Method></Frame><Frame><File>C:\Python33\lib\subprocess.py</File><Line>1112</Line><Method>_execute_child</Method></Frame></Stack></Post><Post><PostId>19479390</PostId><Url>http://stackoverflow.com/questions/19479390</Url><Stack><Type>FileNotFoundError</Type><Message>[WinError 2] The system cannot find the file specified</Message><Frame><File>C:\Python33\lib\subprocess.py</File><Line>1106</Line><Method>_execute_child</Method></Frame><Frame><File>C:\casestudy\opener.py</File><Line>13</Line><Method>module</Method></Frame><Frame><File>C:\casestudy\opener.py</File><Line>5</Line><Method>compile_java</Method></Frame><Frame><File>C:\Python33\lib\subprocess.py</File><Line>539</Line><Method>check_call</Method></Frame><Frame><File>C:\Python33\lib\subprocess.py</File><Line>520</Line><Method>call</Method></Frame><Frame><File>C:\Python33\lib\subprocess.py</File><Line>820</Line><Method>__init__</Method></Frame><Frame><File>C:\Python33\lib\subprocess.py</File><Line>1112</Line><Method>_execute_child</Method></Frame></Stack></Post><Post><PostId>19479390</PostId><Url>http://stackoverflow.com/questions/19479390</Url><Stack><Type>FileNotFoundError</Type><Message>[WinError 2] The system cannot find the file specified</Message><Frame><File>C:\Python33\lib\subprocess.py</File><Line>1106</Line><Method>_execute_child</Method></Frame><Frame><File>C:\casestudy\opener.py</File><Line>13</Line><Method>module</Method></Frame><Frame><File>C:\casestudy\opener.py</File><Line>5</Line><Method>compile_java</Method></Frame><Frame><File>C:\Python33\lib\subprocess.py</File><Line>539</Line><Method>check_call</Method></Frame><Frame><File>C:\Python33\lib\subprocess.py</File><Line>520</Line><Method>call</Method></Frame><Frame><File>C:\Python33\lib\subprocess.py</File><Line>820</Line><Method>__init__</Method></Frame><Frame><File>C:\Python33\lib\subprocess.py</File><Line>1112</Line><Method>_execute_child</Method></Frame></Stack></Post><Post><PostId>19767179</PostId><Url>http://stackoverflow.com/questions/19767179</Url><Stack><Type>FileNotFoundError</Type><Message>[WinError 2] The system cannot find the file specified:'C:\Users\sid\Desktop\test\\images/ds_dataobject.gif.bak'</Message><Frame><File>C:\Users\sid\Desktop\script.py</File><Line>33</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>19819813</PostId><Url>http://stackoverflow.com/questions/19819813</Url><Stack><Type>FileNotFoundError</Type><Message>[Errno 2] No such file or directory: '/Users/burakk/BurakWorks/Web/VIRTUAL_ENVIRONMENTS/django_ozo/bin/easy_install'</Message><Frame><File>/Library/Python/2.7/site-packages/virtualenv.py</File><Line>2270</Line><Method>module</Method></Frame><Frame><File>/Library/Python/2.7/site-packages/virtualenv.py</File><Line>928</Line><Method>main</Method></Frame><Frame><File>/Library/Python/2.7/site-packages/virtualenv.py</File><Line>1042</Line><Method>create_environment</Method></Frame><Frame><File>/Library/Python/2.7/site-packages/virtualenv.py</File><Line>640</Line><Method>install_pip</Method></Frame><Frame><File>/Library/Python/2.7/site-packages/virtualenv.py</File><Line>966</Line><Method>call_subprocess</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/subprocess.py</File><Line>820</Line><Method>__init__</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/subprocess.py</File><Line>1438</Line><Method>_execute_child</Method></Frame></Stack></Post><Post><PostId>20270026</PostId><Url>http://stackoverflow.com/questions/20270026</Url><Stack><Type>FileNotFoundError</Type><Message>[WinError 2] The system cannot find the file specified: 'Sales_Pack_66 Books Ltd.xlsx'</Message><Frame><File>C:/Users/Ryan/Documents/filenamechange.py</File><Line>29</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>21358309</PostId><Url>http://stackoverflow.com/questions/21358309</Url><Stack><Type>FileNotFoundError</Type><Message>[Errno 2] No such file or directory: 'Funky.xls'</Message><Frame><File>pyshell#1</File><Line>1</Line><Method>module</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/xlrd/__init__.py</File><Line>394</Line><Method>open_workbook</Method></Frame></Stack></Post><Post><PostId>22104155</PostId><Url>http://stackoverflow.com/questions/22104155</Url><Stack><Type>FileNotFoundError</Type><Message>[WinError 2] The system cannot find the file specified: 'rsr.txt'</Message><Frame><File>C:\ilmiont_server\blog\homepage.py</File><Line>17</Line><Method>module</Method></Frame><Frame><File>C:\Python33\lib\genericpath.py</File><Line>64</Line><Method>getctime</Method></Frame></Stack></Post><Post><PostId>22366282</PostId><Url>http://stackoverflow.com/questions/22366282</Url><Stack><Type>FileNotFoundError</Type><Message>[Errno 2] No such file or directory: 'example.txt'</Message><Frame><File>C:/Users/FEDROS/Desktop/bs.py</File><Line>9</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>22382609</PostId><Url>http://stackoverflow.com/questions/22382609</Url><Stack><Type>FileNotFoundError</Type><Message>[Errno 2] No such file or directory: './test_Match_1899_pickle.pkl'</Message><Frame><File>/home/travis/build/garth5689/pyd2l/test/pyd2l_test.py</File><Line>70</Line><Method>setUp</Method></Frame></Stack></Post><Post><PostId>22883188</PostId><Url>http://stackoverflow.com/questions/22883188</Url><Stack><Type>FileNotFoundError</Type><Message>[Errno 2] No such file or directory: '/tmp/virtualenvwrapper-                                          initialize-hook-Kxjb02CrwN'</Message><Frame><File>C:\Python34\lib\runpy.py</File><Line>171</Line><Method>_run_module_as_main</Method></Frame><Frame><File>C:\Python34\lib\runpy.py</File><Line>86</Line><Method>_run_code</Method></Frame><Frame><File>C:\Python34\lib\site-packages\virtualenvwrapper-4.2-py3.4.egg\virtualenv                                          wrapper\hook_loader.py</File><Line>217</Line><Method>module</Method></Frame><Frame><File>C:\Python34\lib\site-packages\virtualenvwrapper-4.2-py3.4.egg\virtualenv                                          wrapper\hook_loader.py</File><Line>137</Line><Method>main</Method></Frame></Stack></Post><Post><PostId>23222543</PostId><Url>http://stackoverflow.com/questions/23222543</Url><Stack><Type>FileNotFoundError</Type><Message>[Errno 2] No such file or directory: 'setup_description.rst'</Message><Frame><File>C:\Openlayers\defunkt-pystache-6a54b9a\setup.py</File><Line>413</Line><Method>module</Method></Frame><Frame><File>C:\Openlayers\defunkt-pystache-6a54b9a\setup.py</File><Line>379</Line><Method>main</Method></Frame><Frame><File>C:\Openlayers\defunkt-pystache-6a54b9a\setup.py</File><Line>158</Line><Method>read</Method></Frame></Stack></Post><Post><PostId>23267066</PostId><Url>http://stackoverflow.com/questions/23267066</Url><Stack><Type>FileNotFoundError</Type><Message>[Errno 2] No such file or directory: 'setup_description.rst'</Message><Frame><File>C:\Openlayers\defunkt-pystache-6a54b9a\setup.py</File><Line>413</Line><Method>module</Method></Frame><Frame><File>C:\Openlayers\defunkt-pystache-6a54b9a\setup.py</File><Line>379</Line><Method>main</Method></Frame><Frame><File>C:\Openlayers\defunkt-pystache-6a54b9a\setup.py</File><Line>158</Line><Method>read</Method></Frame></Stack></Post><Post><PostId>23354628</PostId><Url>http://stackoverflow.com/questions/23354628</Url><Stack><Type>FileNotFoundError</Type><Message>[Errno 2] No such file or directory</Message><Frame><File>c:\Python33\lib\site-packages\requests\packages\urllib3\util.py</File><Line>630</Line><Method>ssl_wrap_socket</Method></Frame></Stack></Post><Post><PostId>23796141</PostId><Url>http://stackoverflow.com/questions/23796141</Url><Stack><Type>FileNotFoundError</Type><Message>[Errno 2] No such file or directory: 'cars.txt'</Message><Frame><File>/Users/**********/Downloads/5-13 and 5-15 Files 2/testopen.py</File><Line>2</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>23862339</PostId><Url>http://stackoverflow.com/questions/23862339</Url><Stack><Type>FileNotFoundError</Type><Message>[WinError 2] The system cannot find the file specified:'ib.pdf'-</Message><Frame><File>C:\Users\A\Desktop\script.py</File><Line>5</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>23894175</PostId><Url>http://stackoverflow.com/questions/23894175</Url><Stack><Type>FileNotFoundError</Type><Message>[Errno 2] No such file or directory: ''</Message><Frame><File>/usr/lib/python3.4/tkinter/__init__.py</File><Line>1490</Line><Method>__call__</Method></Frame><Frame><File>/home/ashleymoakes/Desktop/Learning Python/WIP/List Maker/List Maker - Re-Write.py</File><Line>62</Line><Method>lambda</Method></Frame><Frame><File>/home/ashleymoakes/Desktop/Learning Python/WIP/List Maker/List Maker - Re-Write.py</File><Line>17</Line><Method>save_users_list</Method></Frame></Stack></Post><Post><PostId>24023378</PostId><Url>http://stackoverflow.com/questions/24023378</Url><Stack><Type>FileNotFoundError</Type><Message>[WinError 2] The system cannot find the file specified: 'C://py.txt'</Message><Frame><File>pyshell#10</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Python33\lib\site-packages\pysftp.py</File><Line>349</Line><Method>put</Method></Frame><Frame><File>C:\Python33\lib\site-packages\paramiko-1.14.0-       py3.3.egg\paramiko\sftp_client.py</File><Line>585</Line><Method>put</Method></Frame></Stack></Post><Post><PostId>24290668</PostId><Url>http://stackoverflow.com/questions/24290668</Url><Stack><Type>FileNotFoundError</Type><Message>[WinError 2] The system cannot find the file specified</Message><Frame><File>C:\Users\zzz\Documents\SFTPtest.py</File><Line>3</Line><Method>module</Method></Frame><Frame><File>C:\Python33\lib\site-packages\paramiko-1.14.0-py3.3.egg\paramiko\proxy.py</File><Line>49</Line><Method>__init__</Method></Frame><Frame><File>C:\Python33\lib\subprocess.py</File><Line>820</Line><Method>__init__</Method></Frame><Frame><File>C:\Python33\lib\subprocess.py</File><Line>1112</Line><Method>_execute_child</Method></Frame></Stack></Post><Post><PostId>24411238</PostId><Url>http://stackoverflow.com/questions/24411238</Url><Stack><Type>FileNotFoundError</Type><Message>[WinError 2] The system cannot find the file specified</Message><Frame><File>C:\UDP Listener.py</File><Line>42</Line><Method>module</Method></Frame><Frame><File>C:\Python34\lib\subprocess.py</File><Line>858</Line><Method>__init__</Method></Frame><Frame><File>C:\Python34\lib\subprocess.py</File><Line>1111</Line><Method>_execute_child</Method></Frame></Stack></Post><Post><PostId>24619683</PostId><Url>http://stackoverflow.com/questions/24619683</Url><Stack><Type>FileNotFoundError</Type><Message>[Errno 2] No such file or directory: 'C:\\Python34\\libs\\site-packages\\PyQt5\\__init__.py'</Message><Frame><File>C:\Users\Tobal\AppData\Local\Temp\freeze.py</File><Line>103</Line><Method>module</Method></Frame><Frame><File>C:\Users\Tobal\AppData\Local\Temp\freeze.py</File><Line>36</Line><Method>freeze_as_data</Method></Frame><Frame><File>C:\Users\Tobal\AppData\Local\Temp\freeze.py</File><Line>71</Line><Method>_get_marshalled_code</Method></Frame></Stack></Post><Post><PostId>25019085</PostId><Url>http://stackoverflow.com/questions/25019085</Url><Stack><Type>FileNotFoundError</Type><Message>[Errno 2] No such file or directory: '/bin/gpio -g write 23 1</Message><Frame><File>trial.py</File><Line>9</Line><Method>module</Method></Frame><Frame><File>/usr/lib/python3.4/subprocess.py</File><Line>537</Line><Method>call</Method></Frame><Frame><File>/usr/lib/python3.4/subprocess.py</File><Line>858</Line><Method>__init__</Method></Frame><Frame><File>/usr/lib/python3.4/subprocess.py</File><Line>1456</Line><Method>_execute_child</Method></Frame></Stack></Post><Post><PostId>25312561</PostId><Url>http://stackoverflow.com/questions/25312561</Url><Stack><Type>FileNotFoundError</Type><Message>[Errno 2] No such file or directory: 'gs'</Message><Frame><File>/Users/sharland/Dropbox/computing_department/Languages and Systems/python/python_scripts/vine_animations/starburst_pulse.py</File><Line>61</Line><Method>module</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PIL/Image.py</File><Line>1631</Line><Method>save</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PIL/EpsImagePlugin.py</File><Line>361</Line><Method>load</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PIL/EpsImagePlugin.py</File><Line>130</Line><Method>Ghostscript</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py</File><Line>848</Line><Method>__init__</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py</File><Line>1441</Line><Method>_execute_child</Method></Frame></Stack></Post><Post><PostId>25750101</PostId><Url>http://stackoverflow.com/questions/25750101</Url><Stack><Type>FileNotFoundError</Type><Message>[Errno 2] No such file or directory: 'recipeList.txt'</Message><Frame><File>C:/Users/avin__000/Documents/Year 10/I.T/Second controlled Assessment/Python/recipe 2.py</File><Line>95</Line><Method>module</Method></Frame><Frame><File>C:/Users/avin__000/Documents/Year 10/I.T/Second controlled Assessment/Python/recipe 2.py</File><Line>12</Line><Method>modify</Method></Frame></Stack></Post></Posts>