<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>20516750</PostId><Url>http://stackoverflow.com/questions/20516750</Url><Stack><Type>INVALID_CREDENTIALS</Type><Message>{'info': '80090308: LdapErr: DSID-0C0904D1, comment: AcceptSecurityContext error, data 57, v1771', 'desc': 'Invalid credentials'}</Message><Frame><File>workspace/test_ldap_reconnect_bug.py</File><Line>37</Line><Method>test_reconnect</Method></Frame><Frame><File>workspace/test_ldap_reconnect_bug.py</File><Line>14</Line><Method>my_ldap_connect</Method></Frame><Frame><File>/usr/lib64/python2.7/site-packages/ldap/ldapobject.py</File><Line>229</Line><Method>sasl_interactive_bind_s</Method></Frame><Frame><File>/usr/lib64/python2.7/site-packages/ldap/ldapobject.py</File><Line>99</Line><Method>_ldap_call</Method></Frame></Stack></Post></Posts>