<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>12294035</PostId><Url>http://stackoverflow.com/questions/12294035</Url><Stack><Type>NetworkError</Type><Message>Timed out trying to connect to 10.10.10.10 (tried 1 time)</Message><Frame><File>C:\Python27\lib\site-packages\fabric-1.4.1-py2.7.egg\fabric\tasks.py</File><Line>298</Line><Method>execute</Method></Frame><Frame><File>C:\Python27\lib\site-packages\fabric-1.4.1-py2.7.egg\fabric\tasks.py</File><Line>197</Line><Method>_execute</Method></Frame><Frame><File>C:\Python27\lib\site-packages\fabric-1.4.1-py2.7.egg\fabric\tasks.py</File><Line>112</Line><Method>run</Method></Frame><Frame><File>C:\fabfile.py</File><Line>314</Line><Method>generic_task_linux_django</Method></Frame><Frame><File>C:\Python27\lib\site-packages\fabric-1.4.1-py2.7.egg\fabric\network.py</File><Line>457</Line><Method>host_prompting_wrapper</Method></Frame><Frame><File>C:\Python27\lib\site-packages\fabric-1.4.1-py2.7.egg\fabric\operations.py</File><Line>905</Line><Method>run</Method></Frame><Frame><File>C:\Python27\lib\site-packages\fabric-1.4.1-py2.7.egg\fabric\operations.py</File><Line>815</Line><Method>_run_command</Method></Frame><Frame><File>C:\Python27\lib\site-packages\fabric-1.4.1-py2.7.egg\fabric\state.py</File><Line>340</Line><Method>default_channel</Method></Frame><Frame><File>C:\Python27\lib\site-packages\fabric-1.4.1-py2.7.egg\fabric\network.py</File><Line>84</Line><Method>__getitem__</Method></Frame><Frame><File>C:\Python27\lib\site-packages\fabric-1.4.1-py2.7.egg\fabric\network.py</File><Line>76</Line><Method>connect</Method></Frame><Frame><File>C:\Python27\lib\site-packages\fabric-1.4.1-py2.7.egg\fabric\network.py</File><Line>393</Line><Method>connect</Method></Frame></Stack></Post></Posts>