<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>13207450</PostId><Url>http://stackoverflow.com/questions/13207450</Url><Stack><Type>PermissionError</Type><Message>[Errno 13] Permission denied: 'E:\\Python Win7-64-AMD 3.3\\Test\</Message><Frame><File>pyshell#9</File><Line>1</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>13475787</PostId><Url>http://stackoverflow.com/questions/13475787</Url><Stack><Type>PermissionError</Type><Message>[Errno 13] Permission denied</Message><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/3.3/bin/virtualenv</File><Line>9</Line><Method>module</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/virtualenv.py</File><Line>897</Line><Method>main</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/subprocess.py</File><Line>818</Line><Method>__init__</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/subprocess.py</File><Line>1416</Line><Method>_execute_child</Method></Frame></Stack></Post><Post><PostId>14456492</PostId><Url>http://stackoverflow.com/questions/14456492</Url><Stack><Type>PermissionError</Type><Message>[Errno 13] Permission denied</Message><Frame><File>./a.py</File><Line>6</Line><Method>module</Method></Frame><Frame><File>/usr/lib/python3.3/os.py</File><Line>531</Line><Method>execl</Method></Frame></Stack></Post><Post><PostId>15705902</PostId><Url>http://stackoverflow.com/questions/15705902</Url><Stack><Type>PermissionError</Type><Message>[Errno 13] Permission denied: '\\\\blue\\install$\\Tools\\Library'</Message><Frame><File>.\file_reader3.py</File><Line>18</Line><Method>module</Method></Frame><Frame><File>C:\Python33\lib\shutil.py</File><Line>109</Line><Method>copyfile</Method></Frame></Stack></Post><Post><PostId>18963336</PostId><Url>http://stackoverflow.com/questions/18963336</Url><Stack><Type>PermissionError</Type><Message>[WinError 5] Access is denied</Message><Frame><File>C:\Users\Administrator\.eclipse\org.eclipse.platform_4.3.0_1709980481_win32_win32_x86_64\plugins\org.python.pydev_2.8.2.2013090511\pysrc\pydevd.py</File><Line>1446</Line><Method>module</Method></Frame><Frame><File>C:\Users\Administrator\.eclipse\org.eclipse.platform_4.3.0_1709980481_win32_win32_x86_64\plugins\org.python.pydev_2.8.2.2013090511\pysrc\pydevd.py</File><Line>1092</Line><Method>run</Method></Frame><Frame><File>C:\Users\Administrator\.eclipse\org.eclipse.platform_4.3.0_1709980481_win32_win32_x86_64\plugins\org.python.pydev_2.8.2.2013090511\pysrc\_pydev_execfile.py</File><Line>38</Line><Method>execfile</Method></Frame><Frame><File>C:\Users\Administrator\Documents\Kepler\workspace\kr.caleb.python.first\src\fileCopy\xCopyPython.py</File><Line>92</Line><Method>module</Method></Frame><Frame><File>C:\Users\Administrator\Documents\Kepler\workspace\kr.caleb.python.first\src\fileCopy\xCopyPython.py</File><Line>79</Line><Method>dist_files</Method></Frame><Frame><File>C:\Python33\lib\multiprocessing\process.py</File><Line>111</Line><Method>start</Method></Frame><Frame><File>C:\Python33\lib\multiprocessing\forking.py</File><Line>248</Line><Method>__init__</Method></Frame><Frame><File>C:\Python33\lib\multiprocessing\forking.py</File><Line>166</Line><Method>dump</Method></Frame><Frame><File>C:\Python33\lib\multiprocessing\synchronize.py</File><Line>70</Line><Method>__getstate__</Method></Frame><Frame><File>C:\Python33\lib\multiprocessing\forking.py</File><Line>258</Line><Method>duplicate_for_child</Method></Frame><Frame><File>C:\Python33\lib\multiprocessing\forking.py</File><Line>201</Line><Method>duplicate</Method></Frame></Stack></Post><Post><PostId>19731665</PostId><Url>http://stackoverflow.com/questions/19731665</Url><Stack><Type>PermissionError</Type><Message>[WinError 5] Access is denied</Message><Frame><File>C:\Python33\lib\site-packages\psutil\_psmswindows.py</File><Line>190</Line><Method>wrapper</Method></Frame><Frame><File>C:\Python33\lib\site-packages\psutil\_psmswindows.py</File><Line>229</Line><Method>get_process_exe</Method></Frame></Stack></Post><Post><PostId>20371476</PostId><Url>http://stackoverflow.com/questions/20371476</Url><Stack><Type>PermissionError</Type><Message>[Errno 13] Permission denied: 'd:/study'</Message><Frame><File>C:\Users\tzuriel\Desktop\test.py</File><Line>15</Line><Method>open (FILENAME,'w')</Method></Frame></Stack></Post><Post><PostId>20932896</PostId><Url>http://stackoverflow.com/questions/20932896</Url><Stack><Type>PermissionError</Type><Message>[Errno 13] Permission denied: '.\\tmp'</Message><Frame><File>C:\Python33\lib\tkinter\__init__.py</File><Line>1475</Line><Method>__call__</Method></Frame><Frame><File>C:\Python33\lib\site-packages\downloader.py</File><Line>17</Line><Method>startdownload</Method></Frame><Frame><File>C:\Python33\lib\urllib\request.py</File><Line>191</Line><Method>urlretrieve</Method></Frame></Stack></Post><Post><PostId>21719861</PostId><Url>http://stackoverflow.com/questions/21719861</Url><Stack><Type>PermissionError</Type><Message>[Errno 13] Permission denied: 'C:\\Windows\\System32\\oobe\\INFO\\backgrounds\\backgrounddefault.jpg'</Message><Frame><File>C:\Users\Owner\Documents\Wallpaper\Program.py</File><Line>21</Line><Method>module</Method></Frame><Frame><File>C:\Python33\lib\shutil.py</File><Line>243</Line><Method>copy2</Method></Frame><Frame><File>C:\Python33\lib\shutil.py</File><Line>110</Line><Method>copyfile</Method></Frame></Stack></Post><Post><PostId>22130109</PostId><Url>http://stackoverflow.com/questions/22130109</Url><Stack><Type>PermissionError</Type><Message>[WinError 5] Access is denied</Message><Frame><File>C:\Python33\lib\subprocess.py</File><Line>1105</Line><Method>_execute_child</Method></Frame><Frame><File>C:\Python33\lib\site-packages\selenium\webdriver\chrome\service.py</File><Line>63</Line><Method>start</Method></Frame><Frame><File>C:\Python33\lib\subprocess.py</File><Line>817</Line><Method>__init__</Method></Frame><Frame><File>C:\Python33\lib\subprocess.py</File><Line>1111</Line><Method>_execute_child</Method></Frame></Stack></Post><Post><PostId>22130109</PostId><Url>http://stackoverflow.com/questions/22130109</Url><Stack><Type>PermissionError</Type><Message>[WinError 5] Access is denied</Message><Frame><File>C:\Python33\lib\subprocess.py</File><Line>1105</Line><Method>_execute_child</Method></Frame><Frame><File>C:\Python33\lib\site-packages\selenium\webdriver\chrome\service.py</File><Line>63</Line><Method>start</Method></Frame><Frame><File>C:\Python33\lib\subprocess.py</File><Line>817</Line><Method>__init__</Method></Frame><Frame><File>C:\Python33\lib\subprocess.py</File><Line>1111</Line><Method>_execute_child</Method></Frame></Stack></Post><Post><PostId>22130671</PostId><Url>http://stackoverflow.com/questions/22130671</Url><Stack><Type>PermissionError</Type><Message>[Errno 13] Permission denied: 'C:/Users/Wilson/AppData/Local/Google/Chrome/User Data/Default/Extensions'</Message><Frame><File>C:/Users/Wilson/Dropbox/xxx.py</File><Line>77</Line><Method>module</Method></Frame><Frame><File>C:\Python33\lib\site-packages\selenium\webdriver\chrome\webdriver.py</File><Line>55</Line><Method>__init__</Method></Frame><Frame><File>C:\Python33\lib\site-packages\selenium\webdriver\chrome\options.py</File><Line>140</Line><Method>to_capabilities</Method></Frame><Frame><File>C:\Python33\lib\site-packages\selenium\webdriver\chrome\options.py</File><Line>76</Line><Method>extensions</Method></Frame></Stack></Post><Post><PostId>22924717</PostId><Url>http://stackoverflow.com/questions/22924717</Url><Stack><Type>PermissionError</Type><Message>[Errno 13] Permission denied</Message><Frame><File>/var/www/wsgi/lib/python3.3/site-packages/postgresql/protocol/client3.py</File><Line>136</Line><Method>connect</Method></Frame><Frame><File>/var/www/wsgi/lib/python3.3/site-packages/postgresql/python/socket.py</File><Line>64</Line><Method>__call__</Method></Frame></Stack></Post><Post><PostId>23143566</PostId><Url>http://stackoverflow.com/questions/23143566</Url><Stack><Type>PermissionError</Type><Message>[Errno 13] Permission denied: 'website-env/lib'</Message><Frame><File>/usr/local/lib/python3.4/site-packages/virtualenv.py</File><Line>2338</Line><Method>module</Method></Frame><Frame><File>/usr/local/lib/python3.4/site-packages/virtualenv.py</File><Line>824</Line><Method>main</Method></Frame><Frame><File>/usr/local/lib/python3.4/site-packages/virtualenv.py</File><Line>984</Line><Method>create_environment</Method></Frame><Frame><File>/usr/local/lib/python3.4/site-packages/virtualenv.py</File><Line>1158</Line><Method>install_python</Method></Frame><Frame><File>/usr/local/lib/python3.4/site-packages/virtualenv.py</File><Line>447</Line><Method>mkdir</Method></Frame><Frame><File>/usr/local/lib/python3.3/os.py</File><Line>258</Line><Method>makedirs</Method></Frame><Frame><File>/usr/local/lib/python3.3/os.py</File><Line>269</Line><Method>makedirs</Method></Frame></Stack></Post><Post><PostId>23707988</PostId><Url>http://stackoverflow.com/questions/23707988</Url><Stack><Type>PermissionError</Type><Message>[Errno 13] Permission denied</Message><Frame><File>/home/milosz/devel/project_great/.virtualenv/lib/python3.3/site-packages/postgresql/protocol/client3.py</File><Line>136</Line><Method>connect</Method></Frame><Frame><File>/home/milosz/devel/project_great/.virtualenv/lib/python3.3/site-packages/postgresql/python/socket.py</File><Line>64</Line><Method>__call__</Method></Frame></Stack></Post><Post><PostId>23728808</PostId><Url>http://stackoverflow.com/questions/23728808</Url><Stack><Type>PermissionError</Type><Message>[Errno 13] Permission denied: 'C:/Python34/test/New folder'</Message><Frame><File>C:\Python34\test.py</File><Line>51</Line><Method>module</Method></Frame><Frame><File>C:\Python34\test.py</File><Line>17</Line><Method>main</Method></Frame></Stack></Post><Post><PostId>23924223</PostId><Url>http://stackoverflow.com/questions/23924223</Url><Stack><Type>PermissionError</Type><Message>[WinError 5] Access is denied: 'D:\\Backup\\All Pictures'</Message><Frame><File>cpdocsnpics.py</File><Line>17</Line><Method>module</Method></Frame><Frame><File>cpdocsnpics.py</File><Line>10</Line><Method>overwrite</Method></Frame><Frame><File>C:\Python34\lib\shutil.py</File><Line>477</Line><Method>rmtree</Method></Frame><Frame><File>C:\Python34\lib\shutil.py</File><Line>376</Line><Method>_rmtree_unsafe</Method></Frame><Frame><File>C:\Python34\lib\shutil.py</File><Line>374</Line><Method>_rmtree_unsafe</Method></Frame></Stack></Post><Post><PostId>23938156</PostId><Url>http://stackoverflow.com/questions/23938156</Url><Stack><Type>PermissionError</Type><Message>[WinError 5] Access is denied: 'wtf'</Message><Frame><File>wtf.py</File><Line>4</Line><Method>module</Method></Frame><Frame><File>C:\Program Files (x86)\Python34\lib\os.py</File><Line>244</Line><Method>makedirs</Method></Frame></Stack></Post><Post><PostId>23938896</PostId><Url>http://stackoverflow.com/questions/23938896</Url><Stack><Type>PermissionError</Type><Message>[WinError 5] Access is denied: ...</Message><Frame><File>C:\PyEnvs\3.4\lib\shutil.py</File><Line>370</Line><Method>_rmtree_unsafe</Method></Frame></Stack></Post><Post><PostId>24003829</PostId><Url>http://stackoverflow.com/questions/24003829</Url><Stack><Type>PermissionError</Type><Message>[Errno 13] Permission denied: 'C:\\Program Files (x86)\\python\\lib\\site-packages\\win32com\\gen_py\\__init__.py'</Message><Frame><File>pyshell#1</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>56</Line><Method>__init__</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>106</Line><Method>_LoadDicts</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>139</Line><Method>GetGeneratePath</Method></Frame><Frame><File>pyshell#2</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\__init__.py</File><Line>11</Line><Method>module</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>662</Line><Method>module</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>58</Line><Method>__init__</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>649</Line><Method>Rebuild</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>65</Line><Method>_SaveDicts</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>141</Line><Method>GetGeneratePath</Method></Frame></Stack></Post><Post><PostId>24003829</PostId><Url>http://stackoverflow.com/questions/24003829</Url><Stack><Type>PermissionError</Type><Message>[Errno 13] Permission denied: 'C:\\Program Files (x86)\\python\\lib\\site-packages\\win32com\\gen_py\\__init__.py'</Message><Frame><File>pyshell#1</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>56</Line><Method>__init__</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>106</Line><Method>_LoadDicts</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>139</Line><Method>GetGeneratePath</Method></Frame><Frame><File>pyshell#2</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\__init__.py</File><Line>11</Line><Method>module</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>662</Line><Method>module</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>58</Line><Method>__init__</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>649</Line><Method>Rebuild</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>65</Line><Method>_SaveDicts</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>141</Line><Method>GetGeneratePath</Method></Frame></Stack></Post><Post><PostId>24003829</PostId><Url>http://stackoverflow.com/questions/24003829</Url><Stack><Type>PermissionError</Type><Message>[Errno 13] Permission denied: 'C:\\Program Files (x86)\\python\\lib\\site-packages\\win32com\\gen_py\\__init__.py'</Message><Frame><File>pyshell#1</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>56</Line><Method>__init__</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>106</Line><Method>_LoadDicts</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>139</Line><Method>GetGeneratePath</Method></Frame><Frame><File>pyshell#2</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\__init__.py</File><Line>11</Line><Method>module</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>662</Line><Method>module</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>58</Line><Method>__init__</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>649</Line><Method>Rebuild</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>65</Line><Method>_SaveDicts</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>141</Line><Method>GetGeneratePath</Method></Frame></Stack></Post><Post><PostId>24003829</PostId><Url>http://stackoverflow.com/questions/24003829</Url><Stack><Type>PermissionError</Type><Message>[Errno 13] Permission denied: 'C:\\Program Files (x86)\\python\\lib\\site-packages\\win32com\\gen_py\\__init__.py'</Message><Frame><File>pyshell#1</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>56</Line><Method>__init__</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>106</Line><Method>_LoadDicts</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>139</Line><Method>GetGeneratePath</Method></Frame><Frame><File>pyshell#2</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\__init__.py</File><Line>11</Line><Method>module</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>662</Line><Method>module</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>58</Line><Method>__init__</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>649</Line><Method>Rebuild</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>65</Line><Method>_SaveDicts</Method></Frame><Frame><File>C:\Program Files (x86)\python\lib\site-packages\win32com\client\gencache.py</File><Line>141</Line><Method>GetGeneratePath</Method></Frame></Stack></Post><Post><PostId>24005801</PostId><Url>http://stackoverflow.com/questions/24005801</Url><Stack><Type>PermissionError</Type><Message>[Errno 13] Permission denied: 'c:\\Games\\Toribash-4.8'</Message><Frame><File>C:/Users/Pc/Desktop/Python Projects/Python Summative.py</File><Line>5</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>25711420</PostId><Url>http://stackoverflow.com/questions/25711420</Url><Stack><Type>PermissionError</Type><Message>[WinError 5] Access is denied: 'C:\\Users\\User\\AppData\\Local</Message><Frame><File>C:\Python34\lib\shutil.py</File><Line>370</Line><Method>_rmtree_unsafe</Method></Frame><Frame><File>C:\Python34\lib\shutil.py</File><Line>370</Line><Method>_rmtree_unsafe</Method></Frame></Stack></Post><Post><PostId>25711420</PostId><Url>http://stackoverflow.com/questions/25711420</Url><Stack><Type>PermissionError</Type><Message>[WinError 5] Access is denied: 'C:\\Users\\User\\AppData\\Local</Message><Frame><File>C:\Python34\lib\shutil.py</File><Line>370</Line><Method>_rmtree_unsafe</Method></Frame><Frame><File>C:\Python34\lib\shutil.py</File><Line>370</Line><Method>_rmtree_unsafe</Method></Frame></Stack></Post></Posts>