<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>24542699</PostId><Url>http://stackoverflow.com/questions/24542699</Url><Stack><Type>ProxyError</Type><Message>('Cannot connect to proxy.', error(10054, 'An existing connection was forcibly closed by the remote host'))</Message><Frame><File>C:\Python27\Pre-SiDashboard\more_test.py</File><Line>15</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\site-packages\requests-2.3.0-py2.7.egg\requests\api.py</File><Line>55</Line><Method>get</Method></Frame><Frame><File>C:\Python27\lib\site-packages\requests-2.3.0-py2.7.egg\requests\api.py</File><Line>44</Line><Method>request</Method></Frame><Frame><File>C:\Python27\lib\site-packages\requests-2.3.0-py2.7.egg\requests\sessions.py</File><Line>461</Line><Method>request</Method></Frame><Frame><File>C:\Python27\lib\site-packages\requests-2.3.0-py2.7.egg\requests\sessions.py</File><Line>567</Line><Method>send</Method></Frame><Frame><File>C:\Python27\lib\site-packages\requests-2.3.0-py2.7.egg\requests\adapters.py</File><Line>395</Line><Method>send</Method></Frame></Stack></Post></Posts>