<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>4100455</PostId><Url>http://stackoverflow.com/questions/4100455</Url><Stack><Type>RuntimeWarning</Type><Message>not connected</Message><Frame><File>/Volumes/Users/jce/.pyenv/celery/lib/python2.6/site-packages/nose/case.py</File><Line>186</Line><Method>runTest</Method></Frame><Frame><File>/Volumes/Users/jce/.pyenv/celery/lib/python2.6/site-packages/nose/twistedtools.py</File><Line>138</Line><Method>errback</Method></Frame><Frame><File>/Volumes/Users/jce/.pyenv/celery/lib/python2.6/site-packages/twisted/python/failure.py</File><Line>326</Line><Method>raiseException</Method></Frame></Stack></Post><Post><PostId>23184727</PostId><Url>http://stackoverflow.com/questions/23184727</Url><Stack><Type>RuntimeWarning</Type><Message>DateTimeField TaskState.eta received a naive datetime (2014-04-18 17:50:19.547046) while time zone support is active.</Message><Frame><File>/usr/local/lib/python2.7/dist-packages/kombu/async/timer.py</File><Line>171</Line><Method>apply_entry</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/kombu/async/timer.py</File><Line>64</Line><Method>__call__</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/kombu/async/timer.py</File><Line>132</Line><Method>_reschedules</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/celery/events/snapshot.py</File><Line>73</Line><Method>capture</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/celery/events/state.py</File><Line>421</Line><Method>freeze_while</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/celery/events/snapshot.py</File><Line>70</Line><Method>shutter</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/djcelery/snapshot.py</File><Line>145</Line><Method>on_shutter</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/djcelery/snapshot.py</File><Line>139</Line><Method>_handle_tasks</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/djcelery/snapshot.py</File><Line>105</Line><Method>handle_task</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/djcelery/snapshot.py</File><Line>128</Line><Method>update_task</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/djcelery/models.py</File><Line>358</Line><Method>save</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/models/base.py</File><Line>545</Line><Method>save</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/models/base.py</File><Line>573</Line><Method>save_base</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/models/base.py</File><Line>635</Line><Method>_save_table</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/models/base.py</File><Line>679</Line><Method>_do_update</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/models/query.py</File><Line>507</Line><Method>_update</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py</File><Line>975</Line><Method>execute_sql</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py</File><Line>771</Line><Method>execute_sql</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py</File><Line>940</Line><Method>as_sql</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py</File><Line>353</Line><Method>get_db_prep_save</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py</File><Line>914</Line><Method>get_db_prep_value</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py</File><Line>906</Line><Method>get_prep_value</Method></Frame></Stack></Post></Posts>