<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>2198899</PostId><Url>http://stackoverflow.com/questions/2198899</Url><Stack><Type>SearchError</Type><Message>connection to localhost;3312 failed ((10061, 'Connection refused'))</Message><Frame><File>D:\Python25\Lib\site-packages\django\core\servers\basehttp.py</File><Line>280</Line><Method>run</Method></Frame><Frame><File>D:\Python25\Lib\site-packages\django\core\servers\basehttp.py</File><Line>319</Line><Method>finish_response</Method></Frame><Frame><File>D:\Python25\Lib\site-packages\django\http\__init__.py</File><Line>374</Line><Method>__iter__</Method></Frame><Frame><File>D:\zjm_code\sphinx_test\djangosphinx\models.py</File><Line>240</Line><Method>__iter__</Method></Frame><Frame><File>D:\zjm_code\sphinx_test\djangosphinx\models.py</File><Line>404</Line><Method>_get_data</Method></Frame><Frame><File>D:\zjm_code\sphinx_test\djangosphinx\models.py</File><Line>530</Line><Method>_get_results</Method></Frame><Frame><File>D:\zjm_code\sphinx_test\djangosphinx\models.py</File><Line>517</Line><Method>_get_sphinx_results</Method></Frame></Stack></Post></Posts>