<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>3028786</PostId><Url>http://stackoverflow.com/questions/3028786</Url><Stack><Type>SerialException</Type><Message>WriteFile failed ([Error 6] The handle is invalid.)</Message><Frame><File>D:\Alasdair\Documents\Python Scripts\Phone Interface\test.py</File><Line>14</Line><Method>module</Method></Frame><Frame><File>C:\Python26\Lib\site-packages\serial\serialwin32.py</File><Line>255</Line><Method>write</Method></Frame></Stack></Post><Post><PostId>3125289</PostId><Url>http://stackoverflow.com/questions/3125289</Url><Stack><Type>SerialException</Type><Message>ReadFile failed ([Error 6] The handle is invalid.)</Message><Frame><File>pyshell#3</File><Line>1</Line><Method>module</Method></Frame><Frame><File>build\bdist.win-amd64\egg\serial\serialwin32.py</File><Line>236</Line><Method>read</Method></Frame></Stack></Post><Post><PostId>3640812</PostId><Url>http://stackoverflow.com/questions/3640812</Url><Stack><Type>SerialException</Type><Message>WriteFile failed ([Error 6] The handle is invalid.)</Message><Frame><File>pyshell#2</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\site-packages\serial\serialwin32.py</File><Line>255</Line><Method>write</Method></Frame></Stack></Post><Post><PostId>5315193</PostId><Url>http://stackoverflow.com/questions/5315193</Url><Stack><Type>SerialException</Type><Message>could not open port COM6: [Error 1225] The remote system refused the network connection.</Message><Frame><File>C:\Python27\lib\site-packages\win32\lib\win32serviceutil.py</File><Line>806</Line><Method>SvcRun</Method></Frame><Frame><File>C:\Some_Service.py</File><Line>46</Line><Method>SvcDoRun</Method></Frame><Frame><File>Some_Service.py</File><Line>61</Line><Method>main</Method></Frame><Frame><File>Some_Service.py</File><Line>70</Line><Method>open_serial_port</Method></Frame><Frame><File>C:\Python27\lib\site-packages\serial\serialwin32.py</File><Line>56</Line><Method>open</Method></Frame></Stack></Post><Post><PostId>14084770</PostId><Url>http://stackoverflow.com/questions/14084770</Url><Stack><Type>SerialException</Type><Message>could not open port /dev/tty/.usbmodem3d241: [Errno 20] Not a directory: '/dev/tty/.usbmodem3d241'</Message><Frame><File>/Users/ben/Documents/Arduino_to_Python.py</File><Line>5</Line><Method>module</Method></Frame><Frame><File>build/bdist.macosx-10.7-intel/egg/serial/serialutil.py</File><Line>261</Line><Method>__init__</Method></Frame><Frame><File>build/bdist.macosx-10.7-intel/egg/serial/serialposix.py</File><Line>278</Line><Method>open</Method></Frame></Stack></Post><Post><PostId>15074874</PostId><Url>http://stackoverflow.com/questions/15074874</Url><Stack><Type>SerialException</Type><Message>could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'</Message><Frame><File>/usr/lib/python2.7/threading.py</File><Line>551</Line><Method>__bootstrap_inner</Method></Frame><Frame><File>/usr/lib/python2.7/threading.py</File><Line>504</Line><Method>run</Method></Frame><Frame><File>/home/pi/Zombie Python 1.2 (Modified for Pi) (from Adapt 1.7).py</File><Line>147</Line><Method>rx</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/serial/serialutil.py</File><Line>260</Line><Method>__init__</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/serial/serialposix.py</File><Line>276</Line><Method>open</Method></Frame></Stack></Post><Post><PostId>16352583</PostId><Url>http://stackoverflow.com/questions/16352583</Url><Stack><Type>SerialException</Type><Message>device reports readiness to read but returned no data (device disconnected?)</Message><Frame><File>/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/_cprequest.py</File><Line>656</Line><Method>respond</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/lib/encoding.py</File><Line>188</Line><Method>__call__</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/_cpdispatch.py</File><Line>34</Line><Method>__call__</Method></Frame><Frame><File>remote_control_keypad_new52.py</File><Line>677</Line><Method>request</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/_cprequest.py</File><Line>656</Line><Method>respond</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/lib/encoding.py</File><Line>188</Line><Method>__call__</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/_cpdispatch.py</File><Line>34</Line><Method>__call__</Method></Frame><Frame><File>remote_control_keypad_new52.py</File><Line>674</Line><Method>request</Method></Frame><Frame><File>remote_control_keypad_new52.py</File><Line>639</Line><Method>comfort_control</Method></Frame><Frame><File>/usr/lib/python2.7/dist-packages/serial/serialposix.py</File><Line>456</Line><Method>read</Method></Frame></Stack></Post><Post><PostId>16352583</PostId><Url>http://stackoverflow.com/questions/16352583</Url><Stack><Type>SerialException</Type><Message>device reports readiness to read but returned no data (device disconnected?)</Message><Frame><File>/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/_cprequest.py</File><Line>656</Line><Method>respond</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/lib/encoding.py</File><Line>188</Line><Method>__call__</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/_cpdispatch.py</File><Line>34</Line><Method>__call__</Method></Frame><Frame><File>remote_control_keypad_new52.py</File><Line>677</Line><Method>request</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/_cprequest.py</File><Line>656</Line><Method>respond</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/lib/encoding.py</File><Line>188</Line><Method>__call__</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/_cpdispatch.py</File><Line>34</Line><Method>__call__</Method></Frame><Frame><File>remote_control_keypad_new52.py</File><Line>674</Line><Method>request</Method></Frame><Frame><File>remote_control_keypad_new52.py</File><Line>639</Line><Method>comfort_control</Method></Frame><Frame><File>/usr/lib/python2.7/dist-packages/serial/serialposix.py</File><Line>456</Line><Method>read</Method></Frame></Stack></Post><Post><PostId>22469702</PostId><Url>http://stackoverflow.com/questions/22469702</Url><Stack><Type>SerialException</Type><Message>could not open port 'COM3': WindowsError(2, 'The system cannot find the file specified.')</Message><Frame><File>E:\test.py</File><Line>163</Line><Method>module</Method></Frame><Frame><File>E:\test.py</File><Line>69</Line><Method>send</Method></Frame><Frame><File>C:\Python27\lib\site-packages\serial\serialwin32.py</File><Line>295</Line><Method>write</Method></Frame><Frame><File>E:\test.py</File><Line>138</Line><Method>module</Method></Frame><Frame><File>E:\test.py</File><Line>25</Line><Method>__init__</Method></Frame><Frame><File>C:\Python27\lib\site-packages\serial\serialwin32.py</File><Line>38</Line><Method>__init__</Method></Frame><Frame><File>C:\Python27\lib\site-packages\serial\serialutil.py</File><Line>282</Line><Method>__init__</Method></Frame><Frame><File>C:\Python27\lib\site-packages\serial\serialwin32.py</File><Line>66</Line><Method>open</Method></Frame></Stack></Post><Post><PostId>22469702</PostId><Url>http://stackoverflow.com/questions/22469702</Url><Stack><Type>SerialException</Type><Message>could not open port 'COM3': WindowsError(2, 'The system cannot find the file specified.')</Message><Frame><File>E:\test.py</File><Line>163</Line><Method>module</Method></Frame><Frame><File>E:\test.py</File><Line>69</Line><Method>send</Method></Frame><Frame><File>C:\Python27\lib\site-packages\serial\serialwin32.py</File><Line>295</Line><Method>write</Method></Frame><Frame><File>E:\test.py</File><Line>138</Line><Method>module</Method></Frame><Frame><File>E:\test.py</File><Line>25</Line><Method>__init__</Method></Frame><Frame><File>C:\Python27\lib\site-packages\serial\serialwin32.py</File><Line>38</Line><Method>__init__</Method></Frame><Frame><File>C:\Python27\lib\site-packages\serial\serialutil.py</File><Line>282</Line><Method>__init__</Method></Frame><Frame><File>C:\Python27\lib\site-packages\serial\serialwin32.py</File><Line>66</Line><Method>open</Method></Frame></Stack></Post></Posts>