<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>18360198</PostId><Url>http://stackoverflow.com/questions/18360198</Url><Stack><Type>SERVER_DOWN</Type><Message>The LDAP server specified, invalid_ldap_url, did not respond to the connection attempt.</Message><Frame><File>/vagrant/sakai-directory-integration/test_sakaiLdapExtractor.py</File><Line>77</Line><Method>test__get_ldap_connection</Method></Frame><Frame><File>/vagrant/sakai-directory-integration/sakai_ldap_integration.py</File><Line>197</Line><Method>_get_ldap_connection</Method></Frame></Stack></Post></Posts>