<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>399129</PostId><Url>http://stackoverflow.com/questions/399129</Url><Stack><Type>SSLError</Type><Message>[Errno 1] _ssl.c:480: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol</Message><Frame><File>C:/Python26/08_emailconnects/12_29_EmailSendExample_NotWorkingYet.py</File><Line>37</Line><Method>module</Method></Frame><Frame><File>C:\Python26\lib\smtplib.py</File><Line>239</Line><Method>__init__</Method></Frame><Frame><File>C:\Python26\lib\smtplib.py</File><Line>295</Line><Method>connect</Method></Frame><Frame><File>C:\Python26\lib\smtplib.py</File><Line>273</Line><Method>_get_socket</Method></Frame><Frame><File>C:\Python26\lib\socket.py</File><Line>512</Line><Method>create_connection</Method></Frame><Frame><File>C:/Python26/08_emailconnects/12_29_eMAILSendtryin_stripped.py</File><Line>16</Line><Method>module</Method></Frame><Frame><File>C:\Python26\lib\smtplib.py</File><Line>749</Line><Method>__init__</Method></Frame><Frame><File>C:\Python26\lib\smtplib.py</File><Line>239</Line><Method>__init__</Method></Frame><Frame><File>C:\Python26\lib\smtplib.py</File><Line>295</Line><Method>connect</Method></Frame><Frame><File>C:\Python26\lib\smtplib.py</File><Line>755</Line><Method>_get_socket</Method></Frame><Frame><File>C:\Python26\lib\ssl.py</File><Line>350</Line><Method>wrap_socket</Method></Frame><Frame><File>C:\Python26\lib\ssl.py</File><Line>118</Line><Method>__init__</Method></Frame><Frame><File>C:\Python26\lib\ssl.py</File><Line>293</Line><Method>do_handshake</Method></Frame></Stack></Post><Post><PostId>399129</PostId><Url>http://stackoverflow.com/questions/399129</Url><Stack><Type>SSLError</Type><Message>[Errno 1] _ssl.c:480: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol</Message><Frame><File>C:/Python26/08_emailconnects/12_29_EmailSendExample_NotWorkingYet.py</File><Line>37</Line><Method>module</Method></Frame><Frame><File>C:\Python26\lib\smtplib.py</File><Line>239</Line><Method>__init__</Method></Frame><Frame><File>C:\Python26\lib\smtplib.py</File><Line>295</Line><Method>connect</Method></Frame><Frame><File>C:\Python26\lib\smtplib.py</File><Line>273</Line><Method>_get_socket</Method></Frame><Frame><File>C:\Python26\lib\socket.py</File><Line>512</Line><Method>create_connection</Method></Frame><Frame><File>C:/Python26/08_emailconnects/12_29_eMAILSendtryin_stripped.py</File><Line>16</Line><Method>module</Method></Frame><Frame><File>C:\Python26\lib\smtplib.py</File><Line>749</Line><Method>__init__</Method></Frame><Frame><File>C:\Python26\lib\smtplib.py</File><Line>239</Line><Method>__init__</Method></Frame><Frame><File>C:\Python26\lib\smtplib.py</File><Line>295</Line><Method>connect</Method></Frame><Frame><File>C:\Python26\lib\smtplib.py</File><Line>755</Line><Method>_get_socket</Method></Frame><Frame><File>C:\Python26\lib\ssl.py</File><Line>350</Line><Method>wrap_socket</Method></Frame><Frame><File>C:\Python26\lib\ssl.py</File><Line>118</Line><Method>__init__</Method></Frame><Frame><File>C:\Python26\lib\ssl.py</File><Line>293</Line><Method>do_handshake</Method></Frame></Stack></Post><Post><PostId>8247416</PostId><Url>http://stackoverflow.com/questions/8247416</Url><Stack><Type>SSLError</Type><Message>[Errno 1] _ssl.c:1348: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number</Message><Frame><File>C:\Python27\pyrevshell.py</File><Line>467</Line><Method>module</Method></Frame><Frame><File>C:\Python27\pyrevshell.py</File><Line>300</Line><Method>run</Method></Frame><Frame><File>C:\Python27\lib\ssl.py</File><Line>372</Line><Method>wrap_socket</Method></Frame><Frame><File>C:\Python27\lib\ssl.py</File><Line>134</Line><Method>__init__</Method></Frame><Frame><File>C:\Python27\lib\ssl.py</File><Line>296</Line><Method>do_handshake</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py</File><Line>582</Line><Method>process_request_thread</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py</File><Line>323</Line><Method>finish_request</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py</File><Line>639</Line><Method>__init__</Method></Frame><Frame><File>shell_server.py</File><Line>324</Line><Method>handle</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py</File><Line>138</Line><Method>read</Method></Frame></Stack></Post><Post><PostId>8247416</PostId><Url>http://stackoverflow.com/questions/8247416</Url><Stack><Type>SSLError</Type><Message>[Errno 1] _ssl.c:1348: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number</Message><Frame><File>C:\Python27\pyrevshell.py</File><Line>467</Line><Method>module</Method></Frame><Frame><File>C:\Python27\pyrevshell.py</File><Line>300</Line><Method>run</Method></Frame><Frame><File>C:\Python27\lib\ssl.py</File><Line>372</Line><Method>wrap_socket</Method></Frame><Frame><File>C:\Python27\lib\ssl.py</File><Line>134</Line><Method>__init__</Method></Frame><Frame><File>C:\Python27\lib\ssl.py</File><Line>296</Line><Method>do_handshake</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py</File><Line>582</Line><Method>process_request_thread</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py</File><Line>323</Line><Method>finish_request</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py</File><Line>639</Line><Method>__init__</Method></Frame><Frame><File>shell_server.py</File><Line>324</Line><Method>handle</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py</File><Line>138</Line><Method>read</Method></Frame></Stack></Post><Post><PostId>9334873</PostId><Url>http://stackoverflow.com/questions/9334873</Url><Stack><Type>SSLError</Type><Message>The read operation timed out</Message><Frame><File>/usr/lib/python2.7/threading.py</File><Line>552</Line><Method>__bootstrap_inner</Method></Frame><Frame><File>/usr/lib/python2.7/threading.py</File><Line>505</Line><Method>run</Method></Frame><Frame><File>stresstest.py</File><Line>32</Line><Method>threadproc</Method></Frame><Frame><File>stresstest.py</File><Line>76</Line><Method>stressTest</Method></Frame><Frame><File>/usr/lib/python2.7/httplib.py</File><Line>1027</Line><Method>getresponse</Method></Frame><Frame><File>/usr/lib/python2.7/httplib.py</File><Line>407</Line><Method>begin</Method></Frame><Frame><File>/usr/lib/python2.7/httplib.py</File><Line>365</Line><Method>_read_status</Method></Frame><Frame><File>/usr/lib/python2.7/socket.py</File><Line>430</Line><Method>readline</Method></Frame><Frame><File>/usr/lib/python2.7/ssl.py</File><Line>232</Line><Method>recv</Method></Frame><Frame><File>/usr/lib/python2.7/ssl.py</File><Line>151</Line><Method>read</Method></Frame></Stack></Post><Post><PostId>12795012</PostId><Url>http://stackoverflow.com/questions/12795012</Url><Stack><Type>SSLError</Type><Message>[Errno 336265218] _ssl.c:351: error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib</Message><Frame><File>C:\Program Files\Python27\lib\multiprocessing\process.py</File><Line>258</Line><Method>_bootstrap</Method></Frame><Frame><File>C:\workspace\projectc\server\server\clientlistener.py</File><Line>49</Line><Method>run</Method></Frame><Frame><File>C:\Program Files\Python27\lib\ssl.py</File><Line>381</Line><Method>wrap_socket</Method></Frame><Frame><File>C:\Program Files\Python27\lib\ssl.py</File><Line>141</Line><Method>__init__</Method></Frame></Stack></Post><Post><PostId>12896868</PostId><Url>http://stackoverflow.com/questions/12896868</Url><Stack><Type>SSLError</Type><Message>[Errno 8] _ssl.c:1359: EOF occurred in violation of protocol</Message><Frame><File>/usr/local/lib/python2.7/dist-packages/xmpppy-0.5.0rc1-py2.7.egg/xmpp/transports.py</File><Line>153</Line><Method>receive</Method></Frame></Stack></Post><Post><PostId>16869962</PostId><Url>http://stackoverflow.com/questions/16869962</Url><Stack><Type>SSLError</Type><Message>[Errno 1] _ssl.c:1363: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version</Message><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado-3.0.1-py2.7.egg/tornado/iostream.py</File><Line>316</Line><Method>wrapper</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado-3.0.1-py2.7.egg/tornado/stack_context.py</File><Line>241</Line><Method>wrapped</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado-3.0.1-py2.7.egg/tornado/websocket.py</File><Line>643</Line><Method>_on_masked_frame_data</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado-3.0.1-py2.7.egg/tornado/websocket.py</File><Line>680</Line><Method>_on_frame_data</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado-3.0.1-py2.7.egg/tornado/websocket.py</File><Line>582</Line><Method>_receive_frame</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado-3.0.1-py2.7.egg/tornado/iostream.py</File><Line>162</Line><Method>read_bytes</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado-3.0.1-py2.7.egg/tornado/iostream.py</File><Line>398</Line><Method>_try_inline_read</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado-3.0.1-py2.7.egg/tornado/iostream.py</File><Line>414</Line><Method>_read_to_buffer</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/tornado-3.0.1-py2.7.egg/tornado/iostream.py</File><Line>856</Line><Method>read_from_fd</Method></Frame><Frame><File>/usr/lib/python2.7/ssl.py</File><Line>160</Line><Method>read</Method></Frame></Stack></Post><Post><PostId>17363413</PostId><Url>http://stackoverflow.com/questions/17363413</Url><Stack><Type>SSLError</Type><Message>[Errno 8] _ssl.c:1325: EOF occurred in violation of protocol</Message><Frame><File>/usr/lib/python2.6/dist-packages/xmpp/transports.py</File><Line>146</Line><Method>receive</Method></Frame></Stack></Post><Post><PostId>19891993</PostId><Url>http://stackoverflow.com/questions/19891993</Url><Stack><Type>SSLError</Type><Message>The read operation timed out</Message><Frame><File>C:\Python27\lib\site-packages\pip\basecommand.py</File><Line>126</Line><Method>main</Method></Frame><Frame><File>C:\Python27\lib\site-packages\pip\commands\install.py</File><Line>223</Line><Method>run</Method></Frame><Frame><File>C:\Python27\lib\site-packages\pip\req.py</File><Line>961</Line><Method>prepare_files</Method></Frame><Frame><File>C:\Python27\lib\site-packages\pip\req.py</File><Line>1079</Line><Method>unpack_url</Method></Frame><Frame><File>C:\Python27\lib\site-packages\pip\download.py</File><Line>449</Line><Method>unpack_http_url</Method></Frame><Frame><File>C:\Python27\lib\site-packages\pip\download.py</File><Line>367</Line><Method>_download_url</Method></Frame><Frame><File>C:\Python27\lib\socket.py</File><Line>380</Line><Method>read</Method></Frame><Frame><File>C:\Python27\lib\httplib.py</File><Line>561</Line><Method>read</Method></Frame><Frame><File>C:\Python27\lib\socket.py</File><Line>380</Line><Method>read</Method></Frame><Frame><File>C:\Python27\lib\ssl.py</File><Line>232</Line><Method>recv</Method></Frame><Frame><File>C:\Python27\lib\ssl.py</File><Line>151</Line><Method>read</Method></Frame></Stack></Post><Post><PostId>22758031</PostId><Url>http://stackoverflow.com/questions/22758031</Url><Stack><Type>SSLError</Type><Message>hostname '10.76.92.70' doesn't match u'lital.com'</Message><Frame><File>pyshell#43</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\site-packages\requests-2.0.0-py2.7.egg\requests\api.py</File><Line>55</Line><Method>get</Method></Frame><Frame><File>C:\Python27\lib\site-packages\requests-2.0.0-py2.7.egg\requests\api.py</File><Line>44</Line><Method>request</Method></Frame><Frame><File>C:\Python27\lib\site-packages\requests-2.0.0-py2.7.egg\requests\sessions.py</File><Line>357</Line><Method>request</Method></Frame><Frame><File>C:\Python27\lib\site-packages\requests-2.0.0-py2.7.egg\requests\sessions.py</File><Line>460</Line><Method>send</Method></Frame><Frame><File>C:\Python27\lib\site-packages\requests-2.0.0-py2.7.egg\requests\adapters.py</File><Line>358</Line><Method>send</Method></Frame></Stack></Post><Post><PostId>23146662</PostId><Url>http://stackoverflow.com/questions/23146662</Url><Stack><Type>SSLError</Type><Message>[Errno 336445449] _ssl.c:368: error:140DC009:SSL routines:SSL_CTX_use_certificate_chain_file:PEM lib</Message><Frame><File>//anaconda/lib/python2.7/site-packages/zmq/eventloop/ioloop.py</File><Line>346</Line><Method>start</Method></Frame><Frame><File>//anaconda/lib/python2.7/site-packages/tornado/netutil.py</File><Line>167</Line><Method>accept_handler</Method></Frame><Frame><File>//anaconda/lib/python2.7/site-packages/tornado/tcpserver.py</File><Line>217</Line><Method>_handle_connection</Method></Frame><Frame><File>//anaconda/lib/python2.7/site-packages/tornado/netutil.py</File><Line>407</Line><Method>ssl_wrap_socket</Method></Frame><Frame><File>//anaconda/python.app/Contents/lib/python2.7/ssl.py</File><Line>387</Line><Method>wrap_socket</Method></Frame><Frame><File>//anaconda/python.app/Contents/lib/python2.7/ssl.py</File><Line>141</Line><Method>__init__</Method></Frame><Frame><File>//anaconda/lib/python2.7/site-packages/zmq/eventloop/ioloop.py</File><Line>346</Line><Method>start</Method></Frame><Frame><File>//anaconda/lib/python2.7/site-packages/tornado/netutil.py</File><Line>167</Line><Method>accept_handler</Method></Frame><Frame><File>//anaconda/lib/python2.7/site-packages/tornado/tcpserver.py</File><Line>217</Line><Method>_handle_connection</Method></Frame><Frame><File>//anaconda/lib/python2.7/site-packages/tornado/netutil.py</File><Line>407</Line><Method>ssl_wrap_socket</Method></Frame><Frame><File>//anaconda/python.app/Contents/lib/python2.7/ssl.py</File><Line>387</Line><Method>wrap_socket</Method></Frame><Frame><File>//anaconda/python.app/Contents/lib/python2.7/ssl.py</File><Line>141</Line><Method>__init__</Method></Frame></Stack></Post><Post><PostId>23146662</PostId><Url>http://stackoverflow.com/questions/23146662</Url><Stack><Type>SSLError</Type><Message>[Errno 336445449] _ssl.c:368: error:140DC009:SSL routines:SSL_CTX_use_certificate_chain_file:PEM lib</Message><Frame><File>//anaconda/lib/python2.7/site-packages/zmq/eventloop/ioloop.py</File><Line>346</Line><Method>start</Method></Frame><Frame><File>//anaconda/lib/python2.7/site-packages/tornado/netutil.py</File><Line>167</Line><Method>accept_handler</Method></Frame><Frame><File>//anaconda/lib/python2.7/site-packages/tornado/tcpserver.py</File><Line>217</Line><Method>_handle_connection</Method></Frame><Frame><File>//anaconda/lib/python2.7/site-packages/tornado/netutil.py</File><Line>407</Line><Method>ssl_wrap_socket</Method></Frame><Frame><File>//anaconda/python.app/Contents/lib/python2.7/ssl.py</File><Line>387</Line><Method>wrap_socket</Method></Frame><Frame><File>//anaconda/python.app/Contents/lib/python2.7/ssl.py</File><Line>141</Line><Method>__init__</Method></Frame><Frame><File>//anaconda/lib/python2.7/site-packages/zmq/eventloop/ioloop.py</File><Line>346</Line><Method>start</Method></Frame><Frame><File>//anaconda/lib/python2.7/site-packages/tornado/netutil.py</File><Line>167</Line><Method>accept_handler</Method></Frame><Frame><File>//anaconda/lib/python2.7/site-packages/tornado/tcpserver.py</File><Line>217</Line><Method>_handle_connection</Method></Frame><Frame><File>//anaconda/lib/python2.7/site-packages/tornado/netutil.py</File><Line>407</Line><Method>ssl_wrap_socket</Method></Frame><Frame><File>//anaconda/python.app/Contents/lib/python2.7/ssl.py</File><Line>387</Line><Method>wrap_socket</Method></Frame><Frame><File>//anaconda/python.app/Contents/lib/python2.7/ssl.py</File><Line>141</Line><Method>__init__</Method></Frame></Stack></Post><Post><PostId>23164345</PostId><Url>http://stackoverflow.com/questions/23164345</Url><Stack><Type>SSLError</Type><Message>hostname 'ram.rachum.com' doesn't match either of '*.webfaction.com', 'webfaction.com'</Message><Frame><File>pyshell#1</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\site-packages\requests\api.py</File><Line>55</Line><Method>get</Method></Frame><Frame><File>C:\Python27\lib\site-packages\requests\api.py</File><Line>44</Line><Method>request</Method></Frame><Frame><File>C:\Python27\lib\site-packages\requests\sessions.py</File><Line>354</Line><Method>request</Method></Frame><Frame><File>C:\Python27\lib\site-packages\requests\sessions.py</File><Line>460</Line><Method>send</Method></Frame><Frame><File>C:\Python27\lib\site-packages\requests\adapters.py</File><Line>250</Line><Method>send</Method></Frame></Stack></Post><Post><PostId>23523720</PostId><Url>http://stackoverflow.com/questions/23523720</Url><Stack><Type>SSLError</Type><Message>[Errno 336445442] _ssl.c:351: error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib</Message><Frame><File>/nobackup/kdhotre/Intracer/16.0.293/C-Int/3rdparty/python2.6.1/lib/python2.6/site-packages/gevent-1.0-py2.6-linux-x86_64.egg/gevent/greenlet.py</File><Line>327</Line><Method>run</Method></Frame><Frame><File>/nobackup/kdhotre/Intracer/16.0.293/C-Int/3rdparty/python2.6.1/lib/python2.6/site-packages/gevent-1.0-py2.6-linux-x86_64.egg/gevent/server.py</File><Line>102</Line><Method>wrap_socket_and_handle</Method></Frame><Frame><File>/nobackup/kdhotre/Intracer/16.0.293/C-Int/3rdparty/python2.6.1/lib/python2.6/site-packages/gevent-1.0-py2.6-linux-x86_64.egg/gevent/ssl.py</File><Line>383</Line><Method>wrap_socket</Method></Frame><Frame><File>/nobackup/kdhotre/Intracer/16.0.293/C-Int/3rdparty/python2.6.1/lib/python2.6/site-packages/gevent-1.0-py2.6-linux-x86_64.egg/gevent/ssl.py</File><Line>87</Line><Method>__init__</Method></Frame></Stack></Post></Posts>