<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>13368763</PostId><Url>http://stackoverflow.com/questions/13368763</Url><Stack><Type>UnknownError</Type><Message>ApplicationError: 7</Message><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>1511</Line><Method>__call__</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>1505</Line><Method>__call__</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>1253</Line><Method>default_dispatcher</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>1077</Line><Method>__call__</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>547</Line><Method>dispatch</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>545</Line><Method>dispatch</Method></Frame><Frame><File>/base/data/home/apps/s~eventinarea-images/1.362351013166724659/main.py</File><Line>132</Line><Method>post</Method></Frame><Frame><File>/base/data/home/apps/s~eventinarea-images/1.362351013166724659/main.py</File><Line>90</Line><Method>handle_upload</Method></Frame><Frame><File>/base/data/home/apps/s~eventinarea-images/1.362351013166724659/main.py</File><Line>74</Line><Method>write_blob</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/1/google/appengine/api/files/file.py</File><Line>568</Line><Method>finalize</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/1/google/appengine/api/files/file.py</File><Line>291</Line><Method>close</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/1/google/appengine/api/files/file.py</File><Line>427</Line><Method>_make_rpc_call_with_retry</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/1/google/appengine/api/files/file.py</File><Line>252</Line><Method>_make_call</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/1/google/appengine/api/files/file.py</File><Line>186</Line><Method>_raise_app_error</Method></Frame></Stack></Post><Post><PostId>13870975</PostId><Url>http://stackoverflow.com/questions/13870975</Url><Stack><Type>UnknownError</Type><Message>ApplicationError: 7</Message><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>1511</Line><Method>__call__</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>1505</Line><Method>__call__</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>1253</Line><Method>default_dispatcher</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>1077</Line><Method>__call__</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>547</Line><Method>dispatch</Method></Frame><Frame><File>/base/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py</File><Line>545</Line><Method>dispatch</Method></Frame><Frame><File>/base/data/home/apps/myserver/myinstance.363844686987482417/mapreduce/base_handler.py</File><Line>65</Line><Method>post</Method></Frame><Frame><File>/base/data/home/apps/myserver/myinstance.363844686987482417/mapreduce/handlers.py</File><Line>231</Line><Method>handle</Method></Frame><Frame><File>/base/data/home/apps/myserver/myinstance.363844686987482417/mapreduce/output_writers.py</File><Line>631</Line><Method>finalize</Method></Frame><Frame><File>/base/data/home/apps/myserver/myinstance.363844686987482417/mapreduce/lib/files/file.py</File><Line>568</Line><Method>finalize</Method></Frame><Frame><File>/base/data/home/apps/myserver/myinstance.363844686987482417/mapreduce/lib/files/file.py</File><Line>291</Line><Method>close</Method></Frame><Frame><File>/base/data/home/apps/myserver/myinstance.363844686987482417/mapreduce/lib/files/file.py</File><Line>427</Line><Method>_make_rpc_call_with_retry</Method></Frame><Frame><File>/base/data/home/apps/myserver/myinstance.363844686987482417/mapreduce/lib/files/file.py</File><Line>252</Line><Method>_make_call</Method></Frame><Frame><File>/base/data/home/apps/myserver/myinstance.363844686987482417/mapreduce/lib/files/file.py</File><Line>186</Line><Method>_raise_app_error</Method></Frame></Stack></Post></Posts>