<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>1894099</PostId><Url>http://stackoverflow.com/questions/1894099</Url><Stack><Type>ValidationError</Type><Message>This value must be an integer.</Message><Frame><File>C:\Users\A\Documents\PROJECTS\Django\sw2\csv2json.py</File><Line>37</Line><Method>module</Method></Frame><Frame><File>C:\Python26\Lib\site-packages\django\core\management\commands\loaddata.py</File><Line>150</Line><Method>handle</Method></Frame><Frame><File>C:\Python26\lib\site-packages\django\core\serializers\json.py</File><Line>41</Line><Method>Deserializer</Method></Frame><Frame><File>C:\Python26\lib\site-packages\django\core\serializers\python.py</File><Line>95</Line><Method>Deserializer</Method></Frame><Frame><File>C:\Python26\lib\site-packages\django\db\models\fields\__init__.py</File><Line>356</Line><Method>to_python</Method></Frame></Stack></Post><Post><PostId>1894099</PostId><Url>http://stackoverflow.com/questions/1894099</Url><Stack><Type>ValidationError</Type><Message>This value must be an integer.</Message><Frame><File>C:\Users\A\Documents\PROJECTS\Django\sw2\csv2json.py</File><Line>37</Line><Method>module</Method></Frame><Frame><File>C:\Python26\Lib\site-packages\django\core\management\commands\loaddata.py</File><Line>150</Line><Method>handle</Method></Frame><Frame><File>C:\Python26\lib\site-packages\django\core\serializers\json.py</File><Line>41</Line><Method>Deserializer</Method></Frame><Frame><File>C:\Python26\lib\site-packages\django\core\serializers\python.py</File><Line>95</Line><Method>Deserializer</Method></Frame><Frame><File>C:\Python26\lib\site-packages\django\db\models\fields\__init__.py</File><Line>356</Line><Method>to_python</Method></Frame></Stack></Post><Post><PostId>7639453</PostId><Url>http://stackoverflow.com/questions/7639453</Url><Stack><Type>ValidationError</Type><Message>[u'Unknown timezone']</Message><Frame><File>/home/username/virtualenvs/kdmc/lib/python2.7/site-packages/django/core/handlers/base.py</File><Line>111</Line><Method>get_response</Method></Frame><Frame><File>/home/username/virtualenvs/kdmc/lib/python2.7/site-packages/django/contrib/sitemaps/views.py</File><Line>39</Line><Method>sitemap</Method></Frame><Frame><File>/home/username/virtualenvs/kdmc/lib/python2.7/site-packages/django/contrib/sitemaps/__init__.py</File><Line>75</Line><Method>get_urls</Method></Frame><Frame><File>/home/username/virtualenvs/kdmc/lib/python2.7/site-packages/django/db/models/query.py</File><Line>107</Line><Method>_result_iter</Method></Frame><Frame><File>/home/username/virtualenvs/kdmc/lib/python2.7/site-packages/django/db/models/query.py</File><Line>772</Line><Method>_fill_cache</Method></Frame><Frame><File>/home/username/virtualenvs/kdmc/lib/python2.7/site-packages/django/db/models/query.py</File><Line>286</Line><Method>iterator</Method></Frame><Frame><File>/home/username/virtualenvs/kdmc/lib/python2.7/site-packages/django/db/models/base.py</File><Line>297</Line><Method>__init__</Method></Frame><Frame><File>/home/username/virtualenvs/kdmc/lib/python2.7/site-packages/django/db/models/fields/subclassing.py</File><Line>99</Line><Method>__set__</Method></Frame><Frame><File>build/bdist.linux-x86_64/egg/timezones/fields.py</File><Line>43</Line><Method>to_python</Method></Frame><Frame><File>build/bdist.linux-x86_64/egg/timezones/utils.py</File><Line>34</Line><Method>coerce_timezone_value</Method></Frame></Stack></Post><Post><PostId>10183965</PostId><Url>http://stackoverflow.com/questions/10183965</Url><Stack><Type>ValidationError</Type><Message>[u'Enter a valid date/time in YYYY-MM-DD HH:MM[:ss[.uuuuuu]]</Message><Frame><File>/home/mb52089/webapps/smartcarpools_prod/lib/python2.7/django/core/management/commands/loaddata.py</File><Line>169</Line><Method>handle</Method></Frame><Frame><File>/home/mb52089/webapps/smartcarpools_prod/lib/python2.7/django/core/serializers/json.py</File><Line>35</Line><Method>Deserializer</Method></Frame><Frame><File>/home/mb52089/webapps/smartcarpools_prod/lib/python2.7/django/core/serializers/python.py</File><Line>128</Line><Method>Deserializer</Method></Frame><Frame><File>/home/mb52089/webapps/smartcarpools_prod/lib/python2.7/django/db/models/fields/__init__.py</File><Line>710</Line><Method>to_python</Method></Frame></Stack></Post><Post><PostId>13088512</PostId><Url>http://stackoverflow.com/questions/13088512</Url><Stack><Type>ValidationError</Type><Message>[u"'0' value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]</Message><Frame><File>/Users/mirkocrocop/.virtualenvs/toastdriven/lib/python2.7/site-packages/south/migration/migrators.py</File><Line>175</Line><Method>_run_migration</Method></Frame><Frame><File>/Users/mirkocrocop/.virtualenvs/toastdriven/lib/python2.7/site-packages/south/migration/migrators.py</File><Line>57</Line><Method>lambda</Method></Frame><Frame><File>/Users/mirkocrocop/workspace/toastdriven/polls/migrations/0003_auto__add_field_poll_question__add_field_poll_pub_date.py</File><Line>19</Line><Method>forwards</Method></Frame><Frame><File>/Users/mirkocrocop/.virtualenvs/toastdriven/lib/python2.7/site-packages/south/db/sqlite3.py</File><Line>31</Line><Method>add_column</Method></Frame><Frame><File>/Users/mirkocrocop/.virtualenvs/toastdriven/lib/python2.7/site-packages/south/db/sqlite3.py</File><Line>189</Line><Method>_column_sql_for_create</Method></Frame><Frame><File>/Users/mirkocrocop/.virtualenvs/toastdriven/lib/python2.7/site-packages/south/db/generic.py</File><Line>688</Line><Method>column_sql</Method></Frame><Frame><File>/Users/mirkocrocop/.virtualenvs/toastdriven/lib/python2.7/site-packages/django/db/models/fields/__init__.py</File><Line>292</Line><Method>get_db_prep_save</Method></Frame><Frame><File>/Users/mirkocrocop/.virtualenvs/toastdriven/lib/python2.7/site-packages/django/db/models/fields/__init__.py</File><Line>816</Line><Method>get_db_prep_value</Method></Frame><Frame><File>/Users/mirkocrocop/.virtualenvs/toastdriven/lib/python2.7/site-packages/django/db/models/fields/__init__.py</File><Line>801</Line><Method>get_prep_value</Method></Frame><Frame><File>/Users/mirkocrocop/.virtualenvs/toastdriven/lib/python2.7/site-packages/django/db/models/fields/__init__.py</File><Line>785</Line><Method>to_python</Method></Frame></Stack></Post><Post><PostId>14851481</PostId><Url>http://stackoverflow.com/questions/14851481</Url><Stack><Type>ValidationError</Type><Message>{'  junk': 'The input field __junk was not expected.'}</Message><Frame><File>/home/ckan/pyenv/src/ckanext-harvest/ckanext/harvest/harvesters/base.py</File><Line>165</Line><Method>_create_or_update_package</Method></Frame><Frame><File>/home/ckan/pyenv/src/ckan/ckan/logic/action/create.py</File><Line>723</Line><Method>package_create_rest</Method></Frame><Frame><File>/home/ckan/pyenv/src/ckan/ckan/logic/action/create.py</File><Line>137</Line><Method>package_create</Method></Frame></Stack></Post><Post><PostId>16214846</PostId><Url>http://stackoverflow.com/questions/16214846</Url><Stack><Type>ValidationError</Type><Message>['error']</Message><Frame><File>/...py</File><Line>21</Line><Method>test_validate_percent</Method></Frame><Frame><File>/....py</File><Line>25</Line><Method>validate_percent</Method></Frame></Stack></Post><Post><PostId>16847332</PostId><Url>http://stackoverflow.com/questions/16847332</Url><Stack><Type>ValidationError</Type><Message>{'bar': [u'This field cannot be null.']}</Message><Frame><File>~/sandbox/myapp/tests.py</File><Line>14</Line><Method>test_avalue_bvalue_validation</Method></Frame><Frame><File>~/dsbx/local/lib/python2.7/site-packages/django/db/models/fields/related.py</File><Line>408</Line><Method>__set__</Method></Frame><Frame><File>~/dsbx/local/lib/python2.7/site-packages/django/db/utils.py</File><Line>142</Line><Method>_route_db</Method></Frame><Frame><File>~/dsbx/local/lib/python2.7/site-packages/mock.py</File><Line>658</Line><Method>__getattr__</Method></Frame><Frame><File>~/sandbox/myapp/tests.py</File><Line>21</Line><Method>test_method_2</Method></Frame><Frame><File>~/dsbx/local/lib/python2.7/site-packages/django/db/models/fields/related.py</File><Line>405</Line><Method>__set__</Method></Frame><Frame><File>~/sandbox/myapp/tests.py</File><Line>29</Line><Method>test_method_3</Method></Frame><Frame><File>/usr/lib/python2.7/unittest/case.py</File><Line>471</Line><Method>assertRaises</Method></Frame><Frame><File>~/dsbx/local/lib/python2.7/site-packages/django/db/models/base.py</File><Line>926</Line><Method>full_clean</Method></Frame></Stack></Post><Post><PostId>16847332</PostId><Url>http://stackoverflow.com/questions/16847332</Url><Stack><Type>ValidationError</Type><Message>{'bar': [u'This field cannot be null.']}</Message><Frame><File>~/sandbox/myapp/tests.py</File><Line>14</Line><Method>test_avalue_bvalue_validation</Method></Frame><Frame><File>~/dsbx/local/lib/python2.7/site-packages/django/db/models/fields/related.py</File><Line>408</Line><Method>__set__</Method></Frame><Frame><File>~/dsbx/local/lib/python2.7/site-packages/django/db/utils.py</File><Line>142</Line><Method>_route_db</Method></Frame><Frame><File>~/dsbx/local/lib/python2.7/site-packages/mock.py</File><Line>658</Line><Method>__getattr__</Method></Frame><Frame><File>~/sandbox/myapp/tests.py</File><Line>21</Line><Method>test_method_2</Method></Frame><Frame><File>~/dsbx/local/lib/python2.7/site-packages/django/db/models/fields/related.py</File><Line>405</Line><Method>__set__</Method></Frame><Frame><File>~/sandbox/myapp/tests.py</File><Line>29</Line><Method>test_method_3</Method></Frame><Frame><File>/usr/lib/python2.7/unittest/case.py</File><Line>471</Line><Method>assertRaises</Method></Frame><Frame><File>~/dsbx/local/lib/python2.7/site-packages/django/db/models/base.py</File><Line>926</Line><Method>full_clean</Method></Frame></Stack></Post><Post><PostId>16847332</PostId><Url>http://stackoverflow.com/questions/16847332</Url><Stack><Type>ValidationError</Type><Message>{'bar': [u'This field cannot be null.']}</Message><Frame><File>~/sandbox/myapp/tests.py</File><Line>14</Line><Method>test_avalue_bvalue_validation</Method></Frame><Frame><File>~/dsbx/local/lib/python2.7/site-packages/django/db/models/fields/related.py</File><Line>408</Line><Method>__set__</Method></Frame><Frame><File>~/dsbx/local/lib/python2.7/site-packages/django/db/utils.py</File><Line>142</Line><Method>_route_db</Method></Frame><Frame><File>~/dsbx/local/lib/python2.7/site-packages/mock.py</File><Line>658</Line><Method>__getattr__</Method></Frame><Frame><File>~/sandbox/myapp/tests.py</File><Line>21</Line><Method>test_method_2</Method></Frame><Frame><File>~/dsbx/local/lib/python2.7/site-packages/django/db/models/fields/related.py</File><Line>405</Line><Method>__set__</Method></Frame><Frame><File>~/sandbox/myapp/tests.py</File><Line>29</Line><Method>test_method_3</Method></Frame><Frame><File>/usr/lib/python2.7/unittest/case.py</File><Line>471</Line><Method>assertRaises</Method></Frame><Frame><File>~/dsbx/local/lib/python2.7/site-packages/django/db/models/base.py</File><Line>926</Line><Method>full_clean</Method></Frame></Stack></Post><Post><PostId>20354385</PostId><Url>http://stackoverflow.com/questions/20354385</Url><Stack><Type>ValidationError</Type><Message>[u'Location is not valid for company']</Message><Frame><File>/home/djangobox/jobboard/companies/tests.py</File><Line>60</Line><Method>test_jobs_and_locations</Method></Frame><Frame><File>/home/djangobox/jobboard/companies/models.py</File><Line>151</Line><Method>clean</Method></Frame></Stack></Post></Posts>