<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>9195753</PostId><Url>http://stackoverflow.com/questions/9195753</Url><Stack><Type>WebDriverException</Type><Message>Message: u'Modal dialog present'</Message><Frame><File>spyfu_ad_crawler_server.py</File><Line>68</Line><Method>module</Method></Frame><Frame><File>spyfu_ad_crawler_server.py</File><Line>34</Line><Method>main</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/selenium/webdriver/support/wait.py</File><Line>49</Line><Method>until</Method></Frame><Frame><File>spyfu_ad_crawler_server.py</File><Line>34</Line><Method>lambda</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py</File><Line>210</Line><Method>find_element_by_xpath</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py</File><Line>645</Line><Method>find_element</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py</File><Line>153</Line><Method>execute</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py</File><Line>147</Line><Method>check_response</Method></Frame></Stack></Post><Post><PostId>9844469</PostId><Url>http://stackoverflow.com/questions/9844469</Url><Stack><Type>WebDriverException</Type><Message>Message: ''</Message><Frame><File>C:/Documents and Settings/paithankar/Desktop/test</File><Line>6</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\site-packages\selenium\webdriver\firefox\webdriver.py</File><Line>46</Line><Method>__init__</Method></Frame><Frame><File>C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py</File><Line>60</Line><Method>__init__</Method></Frame><Frame><File>C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py</File><Line>102</Line><Method>start_session</Method></Frame><Frame><File>C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py</File><Line>153</Line><Method>execute</Method></Frame><Frame><File>C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py</File><Line>125</Line><Method>check_response</Method></Frame></Stack></Post><Post><PostId>17312849</PostId><Url>http://stackoverflow.com/questions/17312849</Url><Stack><Type>WebDriverException</Type><Message>Message: 'Can\'t load the profile. Profile Dir: /cshome/mwaqar/AEK/tmpgZ0n_J Firefox output: \n(Gecko:32421): Gtk-WARNING **: Unable to locate theme engine in module_path: "clearlooks",\n*** LOG addons.xpi: startup\n*** LOG addons.xpi: checkForChanges\n*** LOG addons.xpi: No changes found\n*** LOG addons.xpi: Add-ons list is invalid, rebuilding\n*** LOG addons.xpi-utils: Opening database\n'</Message><Frame><File>/local/data2/mwaqar/opt/Python-2.7.4/lib/python2.7/threading.py</File><Line>810</Line><Method>__bootstrap_inner</Method></Frame><Frame><File>/local/data2/mwaqar/opt/Python-2.7.4/lib/python2.7/threading.py</File><Line>763</Line><Method>run</Method></Frame><Frame><File>/cshome/mwaqar/AEK/AEK_extract_community.py</File><Line>49</Line><Method>extract_community</Method></Frame><Frame><File>/local/data2/mwaqar/opt/Virtual-Python-2.7.4/lib/python2.7/site-packages/selenium-2.33.0-py2.7.egg/selenium/webdriver/firefox/webdriver.py</File><Line>61</Line><Method>__init__</Method></Frame><Frame><File>/local/data2/mwaqar/opt/Virtual-Python-2.7.4/lib/python2.7/site-packages/selenium-2.33.0-py2.7.egg/selenium/webdriver/firefox/extension_connection.py</File><Line>47</Line><Method>__init__</Method></Frame><Frame><File>/local/data2/mwaqar/opt/Virtual-Python-2.7.4/lib/python2.7/site-packages/selenium-2.33.0-py2.7.egg/selenium/webdriver/firefox/firefox_binary.py</File><Line>51</Line><Method>launch_browser</Method></Frame><Frame><File>/local/data2/mwaqar/opt/Virtual-Python-2.7.4/lib/python2.7/site-packages/selenium-2.33.0-py2.7.egg/selenium/webdriver/firefox/firefox_binary.py</File><Line>95</Line><Method>_wait_until_connectable</Method></Frame></Stack></Post><Post><PostId>18675055</PostId><Url>http://stackoverflow.com/questions/18675055</Url><Stack><Type>WebDriverException</Type><Message>Message: u'waiting for evaluate.js load failed' ; Stacktrace:</Message><Frame><File>/Users/muthu/Desktop/boing.py</File><Line>5</Line><Method>b.execute_script('document.getElementsByName("f")[0].submit()')</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/splinter/driver/webdriver/ strong init /strong .py</File><Line>58</Line><Method>execute_script</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py</File><Line>397</Line><Method>execute_script</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py</File><Line>165</Line><Method>execute</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py</File><Line>158</Line><Method>check_response</Method></Frame></Stack></Post><Post><PostId>19465516</PostId><Url>http://stackoverflow.com/questions/19465516</Url><Stack><Type>WebDriverException</Type><Message>Message: 'The browser appears to have exited before we could connect. The output was: \n(process:22490): GLib-CRITICAL **: g_slice_set_config: assertion `sys_page_size == 0\' failed\nGtk-Message: Failed to load module "canberra-gtk-module"\n*** LOG addons.xpi: startup\n*** LOG addons.xpi: checkForChanges\n*** LOG addons.xpi: No changes found\n/usr/lib/firefox/firefox: relocation error: /tmp/tmpxzNZAo/extensions/fxdriver@googlecode.com/platform/Linux_x86-gcc3/components/libwebdriver-firefox-latest.so: symbol _Znwj, version xul24.0 not defined in file libxul.so with link time reference\n'</Message><Frame><File>selenium_asda.py</File><Line>24</Line><Method>setUp</Method></Frame><Frame><File>/usr/lib/python2.7/site-packages/selenium-2.36.0-py2.7.egg/selenium/webdriver/firefox/webdriver.py</File><Line>60</Line><Method>__init__</Method></Frame><Frame><File>/usr/lib/python2.7/site-packages/selenium-2.36.0-py2.7.egg/selenium/webdriver/firefox/extension_connection.py</File><Line>47</Line><Method>__init__</Method></Frame><Frame><File>/usr/lib/python2.7/site-packages/selenium-2.36.0-py2.7.egg/selenium/webdriver/firefox/firefox_binary.py</File><Line>61</Line><Method>launch_browser</Method></Frame><Frame><File>/usr/lib/python2.7/site-packages/selenium-2.36.0-py2.7.egg/selenium/webdriver/firefox/firefox_binary.py</File><Line>100</Line><Method>_wait_until_connectable</Method></Frame></Stack></Post><Post><PostId>21244632</PostId><Url>http://stackoverflow.com/questions/21244632</Url><Stack><Type>WebDriverException</Type><Message>Message: "The browser appears to have exited before we could connect. The output was: XPCOMGlueLoad error for file /usr/bin/libxpcom.so:\n/usr/bin/libxpcom.so: cannot open shared object file: No such file or directory\nCouldn't load XPCOM.\n"</Message><Frame><File>/opt/my_apps/cpns/core/tests.py</File><Line>771</Line><Method>setUp</Method></Frame><Frame><File>/opt/my_apps/cpns/build/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py</File><Line>59</Line><Method>__init__</Method></Frame><Frame><File>/opt/my_apps/cpns/build/lib/python2.7/site-packages/selenium/webdriver/firefox/extension_connection.py</File><Line>47</Line><Method>__init__</Method></Frame><Frame><File>/opt/my_apps/cpns/build/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py</File><Line>61</Line><Method>launch_browser</Method></Frame><Frame><File>/opt/my_apps/cpns/build/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py</File><Line>100</Line><Method>_wait_until_connectable</Method></Frame></Stack></Post><Post><PostId>24011019</PostId><Url>http://stackoverflow.com/questions/24011019</Url><Stack><Type>WebDriverException</Type><Message>Message: u'f.QueryInterface is not a function' ; Stacktrace:</Message><Frame><File>/home/ubuntu//proj/proj/lib/tests.py</File><Line>1347</Line><Method>test_simple</Method></Frame><Frame><File>/home/ubuntu/proj/venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py</File><Line>185</Line><Method>get</Method></Frame><Frame><File>/home/ubuntu/proj/venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py</File><Line>173</Line><Method>execute</Method></Frame><Frame><File>/home/ubuntu/proj/venv/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py</File><Line>164</Line><Method>check_response</Method></Frame></Stack></Post><Post><PostId>24219473</PostId><Url>http://stackoverflow.com/questions/24219473</Url><Stack><Type>WebDriverException</Type><Message>Message: 'Unable to start phantomjs with ghostdriver.' ; Screenshot: available via screen</Message><Frame><File>/home/scraper/superfish-extension/chrome_3day.py</File><Line>96</Line><Method>module</Method></Frame><Frame><File>/home/scraper/superfish-extension/chrome_3day.py</File><Line>73</Line><Method>main</Method></Frame><Frame><File>/home/scraper/superfish-extension/chrome.py</File><Line>81</Line><Method>use_phantomjs</Method></Frame><Frame><File>/home/scraper/.virtualenvs/superfish/lib/python2.6/site-packages/selenium/webdriver/phantomjs/webdriver.py</File><Line>50</Line><Method>__init__</Method></Frame><Frame><File>/home/scraper/.virtualenvs/superfish/lib/python2.6/site-packages/selenium/webdriver/phantomjs/service.py</File><Line>69</Line><Method>start</Method></Frame></Stack></Post><Post><PostId>24659323</PostId><Url>http://stackoverflow.com/questions/24659323</Url><Stack><Type>WebDriverException</Type><Message>Message: None ; Stacktrace:</Message><Frame><File>C:\Python27\Lib\threading.py</File><Line>808</Line><Method>__bootstrap_inner</Method></Frame><Frame><File>C:\Python27\Lib\threading.py</File><Line>761</Line><Method>run</Method></Frame><Frame><File>C:\Users\Test\projects\net10-test\net10-test\lib\site-        packages\huxley\threadpool.py</File><Line>32</Line><Method>thread</Method></Frame><Frame><File>C:\Users\Test\projects\net10-test\net10-test\lib\site-packages\huxley\cmdline.py</File><Line>69</Line><Method>run_test</Method></Frame><Frame><File>C:\Users\Test\projects\net10-test\net10-test\lib\site-packages\huxley\main.py</File><Line>83</Line><Method>main</Method></Frame><Frame><File>C:\Users\Test\projects\net10-test\net10-test\lib\site-packages\selenium\webdriver\remote\webdriver.py</File><Line>72</Line><Method>__init__</Method></Frame><Frame><File>C:\Users\Test\projects\net10-test\net10-test\lib\site-packages\selenium\webdriver\remote\webdriver.py</File><Line>115</Line><Method>start_session</Method></Frame><Frame><File>C:\Users\Test\projects\net10-test\net10-test\lib\site-packages\selenium\webdriver\remote\webdriver.py</File><Line>166</Line><Method>execute</Method></Frame><Frame><File>C:\Users\Test\projects\net10-test\net10-test\lib\site-packages\selenium\webdriver\remote\errorhandler.py</File><Line>164</Line><Method>check_response</Method></Frame></Stack></Post><Post><PostId>24732623</PostId><Url>http://stackoverflow.com/questions/24732623</Url><Stack><Type>WebDriverException</Type><Message>Message: 'ChromeDriver executable needs to be available in the path.                 Please download from http://chromedriver.storage.googleapis.com/index.html                and read up at http://code.google.com/p/selenium/wiki/ChromeDriver'</Message><Frame><File>/home/uri/projects/viggobackend/source/viggo_backend/tests/selenium_test_case.py</File><Line>103</Line><Method>setUpClass</Method></Frame><Frame><File>/home/uri/.virtualenvs/venv/local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py</File><Line>59</Line><Method>__init__</Method></Frame><Frame><File>/home/uri/.virtualenvs/venv/local/lib/python2.7/site-packages/selenium/webdriver/chrome/service.py</File><Line>68</Line><Method>start</Method></Frame></Stack></Post><Post><PostId>25027385</PostId><Url>http://stackoverflow.com/questions/25027385</Url><Stack><Type>WebDriverException</Type><Message>Message: "The browser appears to have exited before we could connect. The output was: ERROR: ld.so: object 'x_ignore_nofocus.so' from LD_PRELOAD cannot be preloaded: ignored.\nERROR: ld.so: object 'x_ignore_nofocus.so' from LD_PRELOAD cannot be preloaded: ignored.\nERROR: ld.so: object 'x_ignore_nofocus.so' from LD_PRELOAD cannot be preloaded: ignored.\nError: no display specified\n"</Message><Frame><File>test.py</File><Line>58</Line><Method>setUp</Method></Frame><Frame><File>/home/pi/naughton_python/flask/flask/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py</File><Line>59</Line><Method>__init__</Method></Frame><Frame><File>/home/pi/naughton_python/flask/flask/local/lib/python2.7/site-packages/selenium/webdriver/firefox/extension_connection.py</File><Line>47</Line><Method>__init__</Method></Frame><Frame><File>/home/pi/naughton_python/flask/flask/local/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py</File><Line>61</Line><Method>launch_browser</Method></Frame><Frame><File>/home/pi/naughton_python/flask/flask/local/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py</File><Line>100</Line><Method>_wait_until_connectable</Method></Frame></Stack></Post><Post><PostId>25111022</PostId><Url>http://stackoverflow.com/questions/25111022</Url><Stack><Type>WebDriverException</Type><Message>Message: u'a is null' ; Stacktrace:</Message><Frame><File>2.7.4__next__page__test.py</File><Line>44</Line><Method>__call__</Method></Frame><Frame><File>2.7.4__next__page__test.py</File><Line>1202</Line><Method>startapi</Method></Frame><Frame><File>2.7.4__next__page__test.py</File><Line>913</Line><Method>query_literature_online_master_function</Method></Frame><Frame><File>c:\python27\lib\site-packages\selenium-2.37.2-py2.7.egg\selenium\webdriver\common\alert.py</File><Line>54</Line><Method>accept</Method></Frame><Frame><File>c:\python27\lib\site-packages\selenium-2.37.2-py2.7.egg\selenium\webdriver\remote\webdriver.py</File><Line>164</Line><Method>execute</Method></Frame><Frame><File>c:\python27\lib\site-packages\selenium-2.37.2-py2.7.egg\selenium\webdriver\remote\errorhandler.py</File><Line>164</Line><Method>check_response</Method></Frame></Stack></Post><Post><PostId>25654761</PostId><Url>http://stackoverflow.com/questions/25654761</Url><Stack><Type>WebDriverException</Type><Message>Message: 'Can\'t load the profile. Profile Dir: /tmp/tmpXWOMML Firefox output: 1409783847270\taddons.manager\tDEBUG\tLoaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]\n1409783847271\taddons.manager\tDEBUG\tLoaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]</Message><Frame><File>/Applications/web2py.app/Contents/Resources/applications/tukker/functional_tests.py</File><Line>18</Line><Method>setUpClass</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py</File><Line>51</Line><Method>__init__</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/firefox/extension_connection.py</File><Line>46</Line><Method>__init__</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py</File><Line>44</Line><Method>launch_browser</Method></Frame><Frame><File>/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py</File><Line>86</Line><Method>_wait_until_connectable</Method></Frame></Stack></Post></Posts>